import type { Workflow } from '../lib/types'

export const CHARACTER_CREATION_WORKFLOW: Workflow = {
  id: 'srd:workflow:character-creation',
  properties: {
    name: 'Character Creation',
    completion_creates: 'creature.player_character',
    steps: [
      {
        id: 'roll-abilities',
        name: 'Generate Ability Scores',
        component: 'ability-allocator',
        config: { mode: 'generate' },
        required: true,
      },
      {
        id: 'select-race',
        name: 'Choose Race',
        component: 'entity-selector',
        config: { entity_type: 'template.race', display: 'card-grid' },
        required: true,
        depends_on: ['roll-abilities'],
      },
      {
        id: 'select-class',
        name: 'Choose Class',
        component: 'entity-selector',
        config: { entity_type: 'template.class', display: 'card-grid' },
        required: true,
        depends_on: ['select-race'],
      },
      {
        id: 'assign-abilities',
        name: 'Assign Ability Scores',
        component: 'ability-allocator',
        config: { mode: 'assign', show_racial_bonuses: true },
        required: true,
        depends_on: ['roll-abilities', 'select-race', 'select-class'],
      },
      {
        id: 'starting-package',
        name: 'Starting Package',
        component: 'narrative-block',
        config: { text: 'Review your suggested starting package.' },
        required: false,
        depends_on: ['select-class'],
      },
      {
        id: 'racial-class-features',
        name: 'Racial & Class Features',
        component: 'narrative-block',
        config: { text: 'Review your racial and class features.' },
        required: false,
        depends_on: ['assign-abilities'],
      },
      {
        id: 'allocate-skills',
        name: 'Allocate Skills',
        component: 'skill-allocator',
        config: { skills_ref: 'srd:mechanic:skills' },
        required: true,
        depends_on: ['racial-class-features'],
      },
      {
        id: 'select-feats',
        name: 'Choose Feats',
        component: 'entity-selector',
        config: { entity_type: 'rule.feat', filter_eligible: true, display: 'filterable-list' },
        required: true,
        depends_on: ['allocate-skills'],
      },
      {
        id: 'description',
        name: 'Character Description',
        component: 'text-form',
        config: { fields: ['appearance', 'background'] },
        required: false,
        depends_on: ['select-feats'],
      },
      {
        id: 'equipment',
        name: 'Starting Equipment',
        component: 'equipment-allocator',
        config: { starting_gold_ref: 'srd:mechanic:starting-gold' },
        required: false,
        depends_on: ['description'],
      },
      {
        id: 'combat-numbers',
        name: 'Combat Numbers',
        component: 'narrative-block',
        config: { text: 'Review your combat statistics.' },
        required: false,
        depends_on: ['equipment'],
      },
      {
        id: 'details',
        name: 'Character Details',
        component: 'text-form',
        config: {
          fields: ['name', 'player_name', 'alignment', 'deity', 'height', 'weight', 'age', 'eyes', 'hair', 'skin'],
        },
        required: false,
        depends_on: ['combat-numbers'],
      },
    ],
  },
}
