// ─────────────────────────────────────────────────────────────────────────
// D&D 3.5 Gestalt Character Creator — Races Data
// ─────────────────────────────────────────────────────────────────────────

const RACES = [
  // HUMANOIDS - Standard
  { cat: "Human Variants", name: "Human", la: 0, rhd: 0, rhdType: 8, bonuses: {}, traits: ["Bonus feat at 1st level", "4 extra skill points at 1st, +1/level", "Favored class: Any"] },
  { cat: "Human Variants", name: "Half-Elf", la: 0, rhd: 0, rhdType: 8, bonuses: {}, traits: ["Low-light vision", "+1 to Listen/Search/Spot", "Sleep immunity", "Elven blood", "Favored class: Any"] },
  { cat: "Human Variants", name: "Half-Orc", la: 0, rhd: 0, rhdType: 8, bonuses: { str: 2, int: -2, cha: -2 }, traits: ["Darkvision 60 ft", "Orc blood", "Favored class: Barbarian"] },
  // Elves
  { cat: "Elves", name: "Elf, High", la: 0, rhd: 0, rhdType: 8, bonuses: { dex: 2, con: -2 }, traits: ["Low-light vision", "+2 Listen/Search/Spot", "Immune: magic sleep", "Proficiency: longsword/rapier/bows", "Favored class: Wizard"] },
  { cat: "Elves", name: "Elf, Grey", la: 0, rhd: 0, rhdType: 8, bonuses: { dex: 2, con: -2, int: 2, str: -2 }, traits: ["Low-light vision", "+2 Listen/Search/Spot", "Immune: sleep", "+1 DC enchantment/illusion spells", "Favored class: Wizard"] },
  { cat: "Elves", name: "Elf, Wood", la: 0, rhd: 0, rhdType: 8, bonuses: { dex: 2, con: -2, str: 2, int: -2 }, traits: ["Low-light vision", "+2 Listen/Search/Spot", "Immune: sleep", "Favored class: Ranger"] },
  { cat: "Elves", name: "Elf, Wild", la: 0, rhd: 0, rhdType: 8, bonuses: { dex: 2, int: -2 }, traits: ["Low-light vision", "+2 Listen/Search/Spot", "Immune: sleep", "Fleet of foot (+5 ft speed)", "Favored class: Sorcerer"] },
  { cat: "Elves", name: "Elf, Sun (Gold)", la: 0, rhd: 0, rhdType: 8, bonuses: { dex: 2, con: -2, int: 2, str: -2 }, traits: ["Low-light vision", "Immune: sleep", "+1 DC evocation spells", "Favored class: Wizard"] },
  { cat: "Elves", name: "Elf, Moon (Silver)", la: 0, rhd: 0, rhdType: 8, bonuses: { dex: 2, con: -2 }, traits: ["Low-light vision", "Immune: sleep", "Favored class: Wizard/Sorcerer"] },
  { cat: "Elves", name: "Elf, Sea", la: 0, rhd: 0, rhdType: 8, bonuses: { dex: 2, con: 2, int: -2 }, traits: ["Low-light vision", "Swim speed 40 ft", "Breathe water", "Aquatic subtype"] },
  { cat: "Elves", name: "Elf, Snow", la: 0, rhd: 0, rhdType: 8, bonuses: { dex: 2, con: -2, wis: 2 }, traits: ["Low-light vision", "Cold resistance 5", "Favored class: Ranger"] },
  { cat: "Elves", name: "Drow (Dark Elf)", la: 2, rhd: 0, rhdType: 8, bonuses: { dex: 2, con: -2, int: 2, cha: 2 }, traits: ["Darkvision 120 ft", "SR 11+HD", "Dancing Lights/Darkness/Faerie Fire 1/day", "Light sensitivity", "LA +2"] },
  { cat: "Elves", name: "Avariel (Winged Elf)", la: 2, rhd: 0, rhdType: 8, bonuses: { dex: 4, str: -2, con: -2 }, traits: ["Low-light vision", "Fly speed 50 ft (average)", "LA +2"] },
  // Dwarves
  { cat: "Dwarves", name: "Dwarf, Hill", la: 0, rhd: 0, rhdType: 8, bonuses: { con: 2, cha: -2 }, traits: ["Darkvision 60 ft", "Stonecunning", "+2 vs poison/spells", "Favored class: Fighter"] },
  { cat: "Dwarves", name: "Dwarf, Mountain", la: 0, rhd: 0, rhdType: 8, bonuses: { con: 2, cha: -2, str: 2, wis: -2 }, traits: ["Darkvision 60 ft", "Stonecunning", "Proficiency: martial weapons", "Favored class: Fighter"] },
  { cat: "Dwarves", name: "Duergar", la: 1, rhd: 0, rhdType: 8, bonuses: { con: 2, cha: -4, wis: 2 }, traits: ["Darkvision 120 ft", "Immune: paralysis/phantasms/poison", "Enlarge/Invisibility 1/day", "Light sensitivity", "LA +1"] },
  // Halflings
  { cat: "Halflings", name: "Halfling, Lightfoot", la: 0, rhd: 0, rhdType: 8, bonuses: { dex: 2, str: -2 }, traits: ["Small size", "+2 Climb/Jump/Listen/Move Silently", "+1 all saves"] },
  { cat: "Halflings", name: "Halfling, Tallfellow", la: 0, rhd: 0, rhdType: 8, bonuses: { dex: 2, str: -2 }, traits: ["Small size", "+2 Search/Spot", "Find secret doors (elf-like)"] },
  { cat: "Halflings", name: "Halfling, Deep", la: 0, rhd: 0, rhdType: 8, bonuses: { dex: 2, str: -2, wis: 2, cha: -2 }, traits: ["Small size", "Darkvision 60 ft", "+1 all saves"] },
  // Gnomes
  { cat: "Gnomes", name: "Gnome, Rock", la: 0, rhd: 0, rhdType: 8, bonuses: { con: 2, str: -2 }, traits: ["Small", "Low-light vision", "+2 Listen/Craft(Alchemy)", "Spell-likes 1/day", "Favored class: Bard"] },
  { cat: "Gnomes", name: "Gnome, Forest", la: 0, rhd: 0, rhdType: 8, bonuses: { dex: 2, str: -4, wis: 2 }, traits: ["Small", "Low-light vision", "Speak with animals at will", "Natural illusionist (+1 DC)"] },
  { cat: "Gnomes", name: "Svirfneblin (Deep Gnome)", la: 3, rhd: 0, rhdType: 8, bonuses: { dex: 2, wis: 2, str: -2, cha: -4 }, traits: ["Small", "Darkvision 120 ft", "SR 11+level", "Stonecunning", "LA +3"] },
  // Planetouched
  { cat: "Planetouched", name: "Aasimar", la: 1, rhd: 0, rhdType: 8, bonuses: { wis: 2, cha: 2 }, traits: ["Darkvision 60 ft", "Daylight 1/day", "Resist acid/cold/electricity 5", "Outsider traits", "LA +1"] },
  { cat: "Planetouched", name: "Tiefling", la: 1, rhd: 0, rhdType: 8, bonuses: { int: 2, cha: -2 }, traits: ["Darkvision 60 ft", "Darkness 1/day", "Resist cold/fire/electricity 5", "Outsider traits", "LA +1"] },
  { cat: "Planetouched", name: "Air Genasi", la: 1, rhd: 0, rhdType: 8, bonuses: { dex: 2, int: 2, cha: -2, wis: -2 }, traits: ["Darkvision 60 ft", "Levitate 1/day", "Outsider traits", "LA +1"] },
  { cat: "Planetouched", name: "Earth Genasi", la: 1, rhd: 0, rhdType: 8, bonuses: { str: 2, con: 2, wis: -2, cha: -2 }, traits: ["Darkvision 60 ft", "Pass Without Trace 1/day", "LA +1"] },
  { cat: "Planetouched", name: "Fire Genasi", la: 1, rhd: 0, rhdType: 8, bonuses: { int: 2, cha: -2 }, traits: ["Darkvision 60 ft", "Fire resistance 5", "LA +1"] },
  { cat: "Planetouched", name: "Water Genasi", la: 1, rhd: 0, rhdType: 8, bonuses: { con: 2, cha: -2 }, traits: ["Swim speed 30 ft", "Create Water 1/day", "LA +1"] },
  { cat: "Planetouched", name: "Frostblood Orc", la: 1, rhd: 0, rhdType: 8, bonuses: { str: 4, int: -2, cha: -2 }, traits: ["Darkvision 60 ft", "Cold resistance 5", "LA +1"] },
  // Monster Manual I - Humanoids
  { cat: "Monstrous Humanoids", name: "Bugbear", la: 1, rhd: 3, rhdType: 8, bonuses: { str: 4, dex: 2, con: 2, cha: -2 }, traits: ["Medium humanoid (goblinoid)", "Darkvision 60 ft", "Low-light vision", "Scent", "3d8 racial HD", "Natural armor +3", "Move Silently as class skill", "LA +1"] },
  { cat: "Monstrous Humanoids", name: "Gnoll", la: 1, rhd: 2, rhdType: 8, bonuses: { str: 4, con: 2, int: -2, cha: -2 }, traits: ["Medium humanoid (gnoll)", "Darkvision 60 ft", "2d8 racial HD", "Natural armor +1", "LA +1"] },
  { cat: "Monstrous Humanoids", name: "Goblin", la: 0, rhd: 0, rhdType: 8, bonuses: { dex: 2, str: -2, cha: -2 }, traits: ["Small humanoid (goblinoid)", "Darkvision 60 ft", "Ride as class skill", "+4 Move Silently"] },
  { cat: "Monstrous Humanoids", name: "Hobgoblin", la: 1, rhd: 0, rhdType: 8, bonuses: { dex: 2, con: 2 }, traits: ["Medium humanoid (goblinoid)", "Darkvision 60 ft", "Move Silently as class skill", "LA +1"] },
  { cat: "Monstrous Humanoids", name: "Kobold", la: -1, rhd: 0, rhdType: 8, bonuses: { dex: 2, str: -4, con: -2 }, traits: ["Small humanoid (reptilian)", "Darkvision 60 ft", "Natural armor +1", "Crafting bonus", "+2 Search (in underground)", "LA -1 (LA buy-off recommended)"] },
  { cat: "Monstrous Humanoids", name: "Lizardfolk", la: 1, rhd: 2, rhdType: 8, bonuses: { str: 2, con: 2, int: -2, cha: -2 }, traits: ["Medium humanoid (reptilian)", "Hold breath", "Natural armor +5 (scaled hide)", "2d8 racial HD", "Multiattack", "LA +1"] },
  { cat: "Monstrous Humanoids", name: "Merfolk", la: 1, rhd: 0, rhdType: 8, bonuses: { dex: 2, con: 2, cha: 2, str: -2 }, traits: ["Medium humanoid (aquatic)", "Swim speed 50 ft", "Breathe water", "Low-light vision", "LA +1"] },
  { cat: "Monstrous Humanoids", name: "Orc", la: 0, rhd: 0, rhdType: 8, bonuses: { str: 4, int: -2, wis: -2, cha: -2 }, traits: ["Medium humanoid (orc)", "Darkvision 60 ft", "Light sensitivity", "Favored class: Barbarian"] },
  { cat: "Monstrous Humanoids", name: "Troglodyte", la: 2, rhd: 2, rhdType: 8, bonuses: { str: 4, con: 4, int: -2, cha: -4 }, traits: ["Medium humanoid (reptilian)", "Darkvision 60 ft", "Stench aura", "Natural weapons: 2 claws + bite", "2d8 racial HD", "Natural armor +6", "LA +2"] },
  // MM I - Fey & Giants
  { cat: "Giants & Large Humanoids", name: "Ogre", la: 3, rhd: 4, rhdType: 8, bonuses: { str: 10, con: 4, int: -4, cha: -4 }, traits: ["Large giant", "Darkvision 60 ft", "Low-light vision", "4d8 racial HD", "Natural armor +5", "Reach 10 ft", "LA +3"] },
  { cat: "Giants & Large Humanoids", name: "Half-Giant (Goliath)", la: 1, rhd: 0, rhdType: 8, bonuses: { str: 4, con: 2, wis: -2, cha: -2 }, traits: ["Medium/Large humanoid", "+4 Climb/Jump", "Natural armor +1", "Power Attack bonus feat", "LA +1"] },
  { cat: "Giants & Large Humanoids", name: "Troll (Lesser)", la: 5, rhd: 6, rhdType: 8, bonuses: { str: 12, con: 12, int: -6, cha: -4 }, traits: ["Large giant", "Darkvision 90 ft", "Low-light vision", "Regeneration 5 (fire and acid)", "6d8 racial HD", "Natural armor +5", "LA +5"] },
  // Undead (intelligent)
  { cat: "Undead (Playable)", name: "Ghoul", la: 2, rhd: 2, rhdType: 12, bonuses: { str: 2, dex: 2, con: 0 }, traits: ["Medium undead", "Darkvision 60 ft", "Paralyzing touch (DC 12 Fort)", "Stench", "+2 undead racial HD (d12)", "Turn resistance +2", "Undead immunities", "LA +2"] },
  { cat: "Undead (Playable)", name: "Wight", la: 3, rhd: 4, rhdType: 12, bonuses: { str: 0, dex: 2, con: 0 }, traits: ["Medium undead", "Darkvision 60 ft", "Energy drain (1 level)", "4d12 racial HD", "Turn resistance +2", "Undead immunities", "Create spawn", "LA +3"] },
  // Outsiders (playable LA)
  { cat: "Outsiders", name: "Bariaur", la: 1, rhd: 0, rhdType: 8, bonuses: { str: 4, dex: 2, con: 2, int: -2 }, traits: ["Large outsider (chaotic/good)", "Charge (gore attack)", "Magic resistance 10", "Darkvision 60 ft", "LA +1"] },
  { cat: "Outsiders", name: "Bladeling", la: 2, rhd: 0, rhdType: 8, bonuses: { dex: 2, wis: 2, cha: -2 }, traits: ["Medium outsider (lawful/evil)", "Acid/fire resistance 5", "Razored skin (1d4 slashing)", "Darkvision 60 ft", "LA +2"] },
  { cat: "Outsiders", name: "Zenythri", la: 2, rhd: 0, rhdType: 8, bonuses: { dex: 2, wis: 2, cha: 2 }, traits: ["Medium outsider (lawful)", "Immune: disease/poison", "Electricity resistance 10", "Darkvision 60 ft", "LA +2"] },
  { cat: "Outsiders", name: "Cansin", la: 2, rhd: 0, rhdType: 8, bonuses: { dex: 4, cha: 2, wis: -2 }, traits: ["Medium outsider (chaotic)", "Fire/sonic resistance 5", "Darkvision 60 ft", "Fast movement +5 ft", "LA +2"] },
  // Planar Races
  { cat: "Planar Races", name: "Githzerai", la: 2, rhd: 0, rhdType: 8, bonuses: { dex: 6, str: -2, wis: 4, con: -2, int: 2, cha: -2 }, traits: ["Medium humanoid (extraplanar)", "Inertial armor (natural armor)", "Psionic powers: Daze/Feather Fall/Jump/Shatter 1/day", "Darkvision 60 ft", "LA +2"] },
  { cat: "Planar Races", name: "Githyanki", la: 2, rhd: 0, rhdType: 8, bonuses: { str: 2, dex: 2, int: 4, wis: -2, cha: -2 }, traits: ["Medium humanoid (extraplanar)", "Psionic powers: Mage Hand/Blur/Telekinesis 1/day", "SR 5+class level", "Darkvision 60 ft", "LA +2"] },
  { cat: "Planar Races", name: "Raptoran", la: 0, rhd: 0, rhdType: 8, bonuses: { dex: 2, wis: 2, str: -2 }, traits: ["Medium humanoid", "Glide (DC 15 Tumble)", "Fly (at 5th level with feats)", "Proficiency: bows", "+2 Spot/Jump", "Favored class: Ranger"] },
  { cat: "Planar Races", name: "Neraphim", la: 1, rhd: 0, rhdType: 8, bonuses: { str: 4, con: 2, cha: -2, int: -2 }, traits: ["Medium outsider (chaotic)", "Darkvision 60 ft", "Bite attack (1d4)", "Natural armor +2", "LA +1"] },
  // Eberron Races
  { cat: "Eberron Races", name: "Warforged", la: 0, rhd: 0, rhdType: 8, bonuses: { con: 2, wis: -2, cha: -2 }, traits: ["Living construct", "Immune: poison/disease/sleep/paralysis/fatigue/exhaustion", "No need to eat/drink/breathe", "Natural armor +2", "Low-light vision", "Favored class: Fighter"] },
  { cat: "Eberron Races", name: "Shifter", la: 0, rhd: 0, rhdType: 8, bonuses: { dex: 2, wis: -2 }, traits: ["Medium humanoid (shapechanger)", "Shifting 1/day (choose subtype)", "Low-light vision", "Favored class: Ranger"] },
  { cat: "Eberron Races", name: "Changeling", la: 0, rhd: 0, rhdType: 8, bonuses: {}, traits: ["Medium humanoid (shapechanger)", "Minor Change Shape at will (alter appearance)", "Natural linguist", "+2 Bluff/Sense Motive/Spot", "Favored class: Rogue"] },
  { cat: "Eberron Races", name: "Kalashtar", la: 0, rhd: 0, rhdType: 8, bonuses: { wis: 2, cha: 2, str: -2 }, traits: ["Medium humanoid (psionic)", "Mindlink 1/day per Cha mod", "Naturally psionic (1 bonus PP)", "+2 saves vs mind-affecting", "Favored class: Psion"] },
  { cat: "Eberron Races", name: "Daelkyr Half-Blood", la: 1, rhd: 0, rhdType: 8, bonuses: { con: 2, cha: 2, int: 2, wis: -2 }, traits: ["Medium aberration (psionic)", "Aberrant dragonmark", "Natural armor +2", "Darkvision 60 ft", "LA +1"] },
  // Psionic Races (Expanded Psionics Handbook)
  { cat: "Psionic Races", name: "Elan", la: 0, rhd: 0, rhdType: 8, bonuses: { cha: -2 }, traits: ["Medium aberration", "Naturally psionic (2 bonus PP)", "Repletion: spend 1 PP to not eat/drink for 24h", "Resilience: spend 1 PP to reduce damage by 2", "Resistance: spend 1 PP for +4 vs saves", "Favored class: Psion"] },
  { cat: "Psionic Races", name: "Maenad", la: 0, rhd: 0, rhdType: 8, bonuses: {}, traits: ["Medium humanoid (psionic)", "Naturally psionic (2 bonus PP)", "Outburst: +2 Str/Con, -2 AC for 4 rounds", "Sound burst 1/day", "Favored class: Wilder"] },
  { cat: "Psionic Races", name: "Xeph", la: 0, rhd: 0, rhdType: 8, bonuses: { dex: 2, str: -2 }, traits: ["Medium humanoid (psionic)", "Naturally psionic (1 bonus PP)", "Burst: +10 ft move speed for 3 rounds/day", "Low-light vision", "Favored class: Soulknife"] },
  { cat: "Psionic Races", name: "Dromite", la: 0, rhd: 0, rhdType: 8, bonuses: { cha: 2, con: 2, str: -2, wis: -2 }, traits: ["Small monstrous humanoid (psionic)", "Naturally psionic (1 bonus PP)", "Fire/cold/electricity resistance 5 (choose)", "Darkvision 60 ft", "Chitin: natural armor +1", "Favored class: Wilder"] },
  { cat: "Psionic Races", name: "Duegar (Psionic Dwarf)", la: 1, rhd: 0, rhdType: 8, bonuses: { con: 2, cha: -4, wis: 2 }, traits: ["Medium humanoid (dwarf, psionic)", "Darkvision 120 ft", "Immune: paralysis/phantasms/poison", "Naturally psionic (3 bonus PP)", "LA +1"] },
  { cat: "Psionic Races", name: "Half-Giant", la: 1, rhd: 0, rhdType: 8, bonuses: { str: 2, con: 2, wis: -2, cha: -2 }, traits: ["Medium humanoid (giant, psionic)", "Naturally psionic (2 bonus PP)", "Giant's stature: powerful build", "Low-light vision", "LA +1"] },
  // Dragon-Blooded
  { cat: "Dragon-Blooded", name: "Dragonborn of Bahamut", la: 0, rhd: 0, rhdType: 8, bonuses: { con: 2, cha: 2, dex: -2 }, traits: ["Medium humanoid (dragonblood)", "Draconic aspect: choose heart/mind/wings", "Wings (aspect of wings): fly speed 30 ft", "Breath weapon (aspect of heart)", "Darkvision 60 ft", "Favored class: Paladin"] },
  { cat: "Dragon-Blooded", name: "Spellscale", la: 0, rhd: 0, rhdType: 8, bonuses: { cha: 2, con: -2 }, traits: ["Medium humanoid (dragonblood)", "Draconic heritage (choose color)", "Blood quickening: bonus spell-like 1/day", "+2 Spellcraft", "Favored class: Sorcerer"] },
  { cat: "Dragon-Blooded", name: "Half-Dragon (Chromatic)", la: 3, rhd: 0, rhdType: 8, bonuses: { str: 8, con: 2, int: 2, cha: 2 }, traits: ["Medium dragon (augmented)", "Darkvision 60 ft / Low-light vision", "Immunity: sleep/paralysis + energy by color", "Natural armor +4", "Breath weapon (choose energy)", "Natural weapons: 2 claws (1d4) + bite (1d6)", "LA +3"] },
  { cat: "Dragon-Blooded", name: "Half-Dragon (Metallic)", la: 3, rhd: 0, rhdType: 8, bonuses: { str: 8, con: 2, int: 2, cha: 4 }, traits: ["Medium dragon (augmented)", "Darkvision 60 ft / Low-light vision", "Immunity: sleep/paralysis + energy by color", "Natural armor +4", "Breath weapon (choose energy)", "Natural weapons: 2 claws (1d4) + bite (1d6)", "LA +3"] },
  { cat: "Dragon-Blooded", name: "Wyvaran", la: 1, rhd: 0, rhdType: 8, bonuses: { dex: 2, int: -2, cha: -2 }, traits: ["Small dragon (kobold-kin)", "Darkvision 60 ft", "Low-light vision", "Fly speed 30 ft (poor)", "Natural armor +1", "LA +1"] },
  { cat: "Dragon-Blooded", name: "Dragon (Juvenile, Brass)", la: 6, rhd: 12, rhdType: 12, bonuses: { str: 12, con: 6, int: 4, cha: 6, dex: -2 }, traits: ["Large dragon", "Darkvision 120 ft / Low-light vision", "Immune: fire/sleep/paralysis", "12d12 racial HD", "Flight (poor)", "Breath weapon: fire/sleep gas", "SR 17", "Natural armor +8", "LA +6 (high-power campaign)"] },
  { cat: "Dragon-Blooded", name: "Dragon (Juvenile, Silver)", la: 6, rhd: 12, rhdType: 12, bonuses: { str: 12, con: 6, int: 4, cha: 6, dex: -2 }, traits: ["Large dragon", "Darkvision 120 ft / Low-light vision", "Immune: cold/sleep/paralysis", "12d12 racial HD", "Flight", "Breath weapon: cold/paralyzing gas", "SR 17", "Natural armor +8", "LA +6"] },
  // Underdark / Exotic
  { cat: "Underdark & Exotic", name: "Illithid (Mind Flayer)", la: 8, rhd: 8, rhdType: 8, bonuses: { int: 8, wis: 6, cha: 4, str: 2 }, traits: ["Medium aberration", "Darkvision 60 ft", "Psionic powers: Charm/Detect Thoughts/Levitate/Suggestion/Mind Blast", "8d8 racial HD", "Tentacle attacks (extract brain)", "SR 25", "Telepathy 100 ft", "LA +8 (epic campaigns)"] },
  { cat: "Underdark & Exotic", name: "Beholder-kin (Gauth)", la: 5, rhd: 6, rhdType: 8, bonuses: { int: 4, wis: 4, cha: 4, con: 4, str: -4, dex: -4 }, traits: ["Small aberration", "All-around vision", "Flight (perfect)", "6 eye rays (various effects)", "6d8 racial HD", "Antimagic cone (1 eye)", "LA +5 (high power only)"] },
  { cat: "Underdark & Exotic", name: "Yuan-ti Pureblood", la: 2, rhd: 0, rhdType: 8, bonuses: { dex: 2, int: 2, cha: 2 }, traits: ["Medium monstrous humanoid (reptilian)", "Darkvision 60 ft", "Immune: poison", "Spell resistance 14", "Alter Self at will", "Detect Poison at will", "LA +2"] },
  { cat: "Underdark & Exotic", name: "Kuo-Toa", la: 2, rhd: 2, rhdType: 8, bonuses: { str: 2, dex: 2, wis: 4, cha: -2, con: 2 }, traits: ["Medium monstrous humanoid (aquatic)", "Darkvision 60 ft", "Amphibious", "Lightning bolt 1/day", "Adhesive skin (+4 grapple)", "2d8 racial HD", "LA +2"] },
  { cat: "Underdark & Exotic", name: "Derro", la: 3, rhd: 3, rhdType: 8, bonuses: { dex: 4, con: 2, str: -2, wis: -6 }, traits: ["Small aberration", "Darkvision 60 ft", "Immune: paralysis/poison/disease", "Spell-like abilities (various)", "3d8 racial HD", "LA +3"] },
  { cat: "Underdark & Exotic", name: "Svirfneblin (Gnome)", la: 3, rhd: 0, rhdType: 8, bonuses: { dex: 2, wis: 2, str: -2, cha: -4 }, traits: ["Small humanoid", "Darkvision 120 ft", "SR 11+level", "Stonecunning", "LA +3"] },
  // Feral / Wild
  { cat: "Feral & Monstrous", name: "Centaur", la: 3, rhd: 4, rhdType: 8, bonuses: { str: 8, con: 4, dex: 2, int: -2, wis: 0, cha: 0 }, traits: ["Large monstrous humanoid", "4d8 racial HD", "+1 natural armor", "Trample (2d6+9)", "Speed 50 ft", "Powerful Build", "LA +3"] },
  { cat: "Feral & Monstrous", name: "Minotaur", la: 2, rhd: 6, rhdType: 8, bonuses: { str: 8, con: 4, int: -4, cha: -2 }, traits: ["Large monstrous humanoid", "Darkvision 60 ft", "Gore attack (1d8)", "6d8 racial HD", "Natural armor +5", "Natural cunning (immune: maze/never lost)", "Power Attack (bonus)", "LA +2"] },
  { cat: "Feral & Monstrous", name: "Harpy", la: 2, rhd: 7, rhdType: 8, bonuses: { dex: 4, con: 2, int: -4, wis: -4, cha: 4, str: 2 }, traits: ["Medium monstrous humanoid", "Fly speed 80 ft (average)", "7d8 racial HD", "Captivating Song (Will DC 11+Cha)", "Natural weapons: 2 talons (1d3)", "LA +2"] },
  { cat: "Feral & Monstrous", name: "Satyr", la: 2, rhd: 5, rhdType: 8, bonuses: { dex: 4, con: 0, int: 2, wis: 0, cha: 4, str: 4 }, traits: ["Medium fey", "Low-light vision", "5d6 racial HD (fey)", "Pipes of the Satyr (charm/sleep/fear)", "Natural weapons: gore (1d6)", "SR 14", "LA +2"] },
  { cat: "Feral & Monstrous", name: "Skulk", la: 1, rhd: 0, rhdType: 8, bonuses: { dex: 2, cha: -2 }, traits: ["Medium humanoid (human-derived)", "Natural camouflage (+8 Hide in outdoor settings)", "+2 Move Silently", "Undetectable alignment", "LA +1"] },
  // Constructs (intelligent, playable)
  { cat: "Constructs & Unusual", name: "Warforged Titan (Scout)", la: 2, rhd: 0, rhdType: 8, bonuses: { str: 4, con: 4, int: -2, cha: -2 }, traits: ["Large living construct", "Natural armor +6", "Immune: poison/disease/sleep/paralysis", "DR 3/adamantine", "Favored class: Fighter", "LA +2"] },
  { cat: "Constructs & Unusual", name: "Stonechild", la: 4, rhd: 6, rhdType: 8, bonuses: { str: 6, con: 4, int: -2, cha: -2 }, traits: ["Medium monstrous humanoid (earth)", "Darkvision 60 ft", "DR 5/adamantine", "6d8 racial HD", "Natural armor +7", "Earth Glide", "LA +4"] },
  { cat: "Constructs & Unusual", name: "Golem-Kin (Iron)", la: 3, rhd: 0, rhdType: 8, bonuses: { str: 6, con: 4, int: -2, cha: -4 }, traits: ["Medium construct (living steel)", "DR 5/adamantine", "Natural armor +5", "Immune: poison/disease/magic sleep", "Darkvision 60 ft", "LA +3"] },
  // Water & Aquatic
  { cat: "Aquatic Races", name: "Triton", la: 2, rhd: 3, rhdType: 8, bonuses: { str: 2, dex: 2, con: 0, cha: 0 }, traits: ["Medium monstrous humanoid (aquatic)", "Darkvision 60 ft", "Swim speed 40 ft", "Breathe water", "3d8 racial HD", "Natural armor +2", "LA +2"] },
  { cat: "Aquatic Races", name: "Locathah", la: 0, rhd: 2, rhdType: 8, bonuses: { dex: 2, int: -2 }, traits: ["Medium humanoid (aquatic)", "Darkvision 60 ft", "Swim speed 60 ft", "Breathe water", "2d8 racial HD", "Natural armor +3"] },
  { cat: "Aquatic Races", name: "Sahuagin", la: 2, rhd: 2, rhdType: 8, bonuses: { str: 4, con: 2, dex: 2, int: 2, wis: 2, cha: -2 }, traits: ["Medium monstrous humanoid (aquatic)", "Darkvision 60 ft", "Blindsense 30 ft (in water)", "2d8 racial HD", "Natural weapons: bite+claws", "Blood frenzy", "LA +2"] },
  // MM II & III Races
  { cat: "MM II & III", name: "Abyssal Maw Demon-Kin", la: 3, rhd: 3, rhdType: 8, bonuses: { str: 4, con: 4, int: -2, cha: -2 }, traits: ["Medium outsider (chaotic evil)", "Darkvision 60 ft", "3d8 racial HD", "Natural armor +4", "Bite attack (1d6)", "Immune: electricity/poison", "LA +3"] },
  { cat: "MM II & III", name: "Aranea", la: 4, rhd: 3, rhdType: 8, bonuses: { int: 4, wis: 2, cha: 4, str: 2 }, traits: ["Medium magical beast (shapechanger)", "Darkvision 60 ft", "3d8 racial HD", "Web (as spider)", "Poison (sleep)", "Alternate Form: spider/human hybrid", "Arcane spellcasting (2nd level Sorcerer)", "LA +4"] },
  { cat: "MM II & III", name: "Cerulean", la: 2, rhd: 0, rhdType: 8, bonuses: { int: 4, wis: 2, dex: 2, str: -2 }, traits: ["Medium humanoid (aquatic, psionic)", "Darkvision 60 ft", "Swim speed 40 ft", "Naturally psionic (3 bonus PP)", "LA +2"] },
  { cat: "MM II & III", name: "Feral Gargun", la: 1, rhd: 3, rhdType: 8, bonuses: { str: 6, con: 4, int: -4, cha: -4 }, traits: ["Large monstrous humanoid", "Darkvision 60 ft", "3d8 racial HD", "Natural armor +4", "Rend (2d6+9 if both claws hit)", "LA +1"] },
  { cat: "MM II & III", name: "Neogi", la: 4, rhd: 3, rhdType: 8, bonuses: { dex: 4, int: 4, wis: 2, str: -4, con: 0, cha: 2 }, traits: ["Small aberration", "Darkvision 60 ft", "3d8 racial HD", "Poison (save vs CON damage)", "Web at will", "Enslave (as hold monster)", "LA +4"] },
  { cat: "MM II & III", name: "Shadow", la: 4, rhd: 3, rhdType: 12, bonuses: { dex: 6, str: 0, con: 0, int: 2, wis: 2, cha: 4 }, traits: ["Medium undead (incorporeal)", "3d12 racial HD (undead)", "Darkvision 60 ft", "Incorporeal: 50% miss chance", "Strength damage on hit", "Create spawn", "Undead immunities", "LA +4"] },
  { cat: "MM II & III", name: "Tauric (Centaur-base)", la: 2, rhd: 4, rhdType: 8, bonuses: { str: 6, con: 2, dex: 2 }, traits: ["Large monstrous humanoid", "4d8 racial HD", "Speed 50 ft", "Natural armor +2", "Can wear humanoid armor on upper torso", "Trample attack", "LA +2"] },
  { cat: "MM II & III", name: "Xill", la: 6, rhd: 5, rhdType: 8, bonuses: { str: 6, dex: 6, con: 2, int: 2 }, traits: ["Medium outsider (evil, extraplanar)", "5d8 racial HD", "Darkvision 60 ft", "4 arms (2 extra attacks)", "Ethereal Jaunt 1/day", "Implant eggs (paralyze + implant)", "LA +6"] },
  // Additional playable options
  { cat: "Underdark & Exotic", name: "Grimlock", la: 1, rhd: 2, rhdType: 8, bonuses: { str: 4, con: 2, dex: 2, wis: -2, cha: -4 }, traits: ["Medium monstrous humanoid", "Blindsight 40 ft", "2d8 racial HD", "Immune: gaze attacks/visual illusions/blinding", "LA +1"] },
  { cat: "Underdark & Exotic", name: "Slyph", la: 2, rhd: 0, rhdType: 8, bonuses: { dex: 4, wis: 2, con: -2, cha: 2 }, traits: ["Small fey (air-touched)", "Fly speed 40 ft (perfect)", "SR 12", "Immune: electricity", "Low-light vision", "LA +2"] },
  { cat: "Planar Races", name: "Tanar'ri Half-Blood", la: 3, rhd: 0, rhdType: 8, bonuses: { str: 4, cha: 4, int: 2, con: 2, wis: -2 }, traits: ["Medium outsider (chaotic evil)", "Darkvision 60 ft", "Immune: electricity/poison", "Resist acid/cold/fire 10", "SR 11+level", "Telepathy 100 ft", "LA +3"] },
  { cat: "Planar Races", name: "Celestial Half-Blood", la: 3, rhd: 0, rhdType: 8, bonuses: { wis: 4, cha: 4, con: 2, int: 2 }, traits: ["Medium outsider (good)", "Darkvision 60 ft", "Immune: disease", "Resist acid/cold/electricity 10", "SR 11+level", "LA +3"] },
  // ── Yuan-ti variants (Serpent Kingdoms / Monster Manual)
  { cat: "Yuan-ti", name: "Yuan-ti Halfblood", la: 3, rhd: 7, rhdType: 8, bonuses: { str: 4, dex: 2, int: 4, wis: 4, cha: 2, con: 2 }, traits: ["Medium monstrous humanoid (reptilian)", "7d8 racial HD", "Darkvision 60 ft", "Immune: poison", "SR 16", "Produce Acid", "Alternate Form (humanoid/snake hybrid)", "Chameleon Power", "Detect Poison at will", "LA +3"] },
  { cat: "Yuan-ti", name: "Yuan-ti Abomination", la: 4, rhd: 9, rhdType: 8, bonuses: { str: 8, dex: 2, int: 6, wis: 4, cha: 2, con: 4 }, traits: ["Large monstrous humanoid (reptilian)", "9d8 racial HD", "Darkvision 60 ft", "Immune: poison", "SR 18", "Constrict/Improved Grab", "Produce Acid 1/day", "Spell-like abilities (multiple)", "LA +4"] },
  // ── Thri-Kreen (Expanded Psionics Handbook / Monster Manual II)
  { cat: "Insectfolk", name: "Thri-Kreen", la: 2, rhd: 2, rhdType: 8, bonuses: { str: 2, dex: 4, int: -2, wis: 2, cha: -4 }, traits: ["Medium monstrous humanoid (psionic)", "2d8 racial HD", "Darkvision 60 ft", "Immune: magic sleep", "Speed 40 ft", "Natural armor +3", "4 arms (Multiweapon Fighting available)", "Natural weapons: 4 claws (1d4) + bite (1d4, poison)", "Poison (bite): 1d6 Dex, paralysis", "Leap: +30 racial bonus Jump", "Psi-like: Chameleon/Know Direction 3/day, Displacement/Metaphysical Weapon 1/day", "Deflect Arrows bonus feat", "LA +2"] },
  // ── Spellweaver (Monster Manual II)
  { cat: "Underdark & Exotic", name: "Spellweaver", la: 4, rhd: 5, rhdType: 8, bonuses: { int: 8, wis: 4, dex: 2, str: -4, cha: 2 }, traits: ["Medium aberration", "5d8 racial HD", "Darkvision 60 ft", "6 arms (3 pairs)", "Spellweaving: cast up to 6 spells simultaneously (one per arm)", "Arcane spellcasting (Wizard, Int-based)", "Detect Magic at will", "SR 18", "Natural armor +4", "LA +4"] },
  // ── Races of the Wild
  { cat: "Races of the Wild", name: "Killoren", la: 0, rhd: 0, rhdType: 8, bonuses: {}, traits: ["Medium fey", "Manifest nature's might (su): choose ancient/hunter/destroyer aspect 1/day", "+2 Sense Motive", "Low-light vision", "Favored class: Druid"] },
  { cat: "Races of the Wild", name: "Catfolk", la: 0, rhd: 0, rhdType: 8, bonuses: { dex: 2, wis: -2 }, traits: ["Medium humanoid (catfolk)", "Low-light vision", "Natural weapons: 2 claws (1d3)", "Sprint 1/hour (10× speed for 1 round)", "+2 Balance/Jump", "Favored class: Ranger"] },
  { cat: "Races of the Wild", name: "Hadozee (Deck Ape)", la: 0, rhd: 0, rhdType: 8, bonuses: { dex: 2, int: -2, wis: 2 }, traits: ["Medium humanoid (hadozee)", "Glide (wing-flaps, up to 60 ft per 10 ft dropped)", "Armor check penalty reduced by 2 on Climb", "+4 Climb", "Low-light vision", "Favored class: Ranger"] },
  // ── Races of Stone
  { cat: "Races of Stone", name: "Goliath", la: 1, rhd: 0, rhdType: 8, bonuses: { str: 4, con: 2, wis: -2, cha: -2 }, traits: ["Medium humanoid (goliath)", "Powerful Build: treat as Large for carry/grapple/special attacks", "+4 Climb/Jump", "Mountain Movement (not slowed by uneven stone)", "Natural Athlete (+2 all Str/Con checks)", "+1 natural armor", "LA +1"] },
  { cat: "Races of Stone", name: "Gnome, Whisper", la: 0, rhd: 0, rhdType: 8, bonuses: { dex: 2, str: -2, cha: -2 }, traits: ["Small humanoid (gnome)", "Low-light vision", "Silence 1/day as spell-like ability", "+4 Hide/Move Silently", "Favored class: Rogue"] },
  { cat: "Races of Stone", name: "Gnome, Wavecrest", la: 0, rhd: 0, rhdType: 8, bonuses: { con: 2, str: -2, int: -2 }, traits: ["Small humanoid (gnome)", "Low-light vision", "Swim speed 30 ft", "Hold breath", "Speak with fish at will", "Favored class: Bard"] },
  // ── Races of Destiny
  { cat: "Races of Destiny", name: "Illumian", la: 0, rhd: 0, rhdType: 8, bonuses: {}, traits: ["Medium humanoid (human, illumian)", "Glowing sigils above head", "Sigil powers: choose 2 of 8 (power sigils grant unique bonuses)", "+2 on checks related to chosen sigils", "Luminous field (dim light 5 ft radius)", "Favored class: Any"] },
  { cat: "Races of Destiny", name: "Mongrelfolk", la: 0, rhd: 0, rhdType: 8, bonuses: { con: 2, int: -2, cha: -4 }, traits: ["Medium humanoid (human-derived)", "Emulate Race (use magic items of any race)", "+2 Listen/Search/Spot", "Darkvision 60 ft", "Low-light vision", "Favored class: Rogue"] },
  { cat: "Races of Destiny", name: "Half-Ogre (Ogrillon)", la: 2, rhd: 0, rhdType: 8, bonuses: { str: 6, con: 2, int: -2, cha: -2 }, traits: ["Medium humanoid (giant-derived)", "Powerful Build", "Natural armor +2", "Darkvision 60 ft", "Low-light vision", "LA +2"] },
  { cat: "Races of Destiny", name: "Darfellan", la: 0, rhd: 0, rhdType: 8, bonuses: { str: 2, dex: -2 }, traits: ["Medium humanoid (darfellan)", "Swim speed 40 ft", "Blindsense 30 ft (in water)", "Echolocation (sonar 30 ft in water)", "+8 Swim", "Hold breath 10 min", "Favored class: Barbarian"] },
  // ── Races of the Dragon
  { cat: "Races of the Dragon", name: "Dragonborn", la: 0, rhd: 0, rhdType: 8, bonuses: { con: 2, dex: -2 }, traits: ["Medium humanoid (base race + dragonblood)", "Rebirth ritual replaces old racial traits", "Choose draconic aspect: Heart (breath weapon), Mind (+2 Int/Wis), or Wings (fly speed 30 ft)", "Darkvision 60 ft", "Immunity to sleep/paralysis", "Favored class: Fighter + base race's"] },
  { cat: "Races of the Dragon", name: "Kobold, Standard", la: -1, rhd: 0, rhdType: 8, bonuses: { dex: 2, str: -4, con: -2 }, traits: ["Small humanoid (reptilian, dragonblood)", "Darkvision 60 ft", "Natural armor +1", "+2 Craft (trapmaking)/Search/Profession (miner)", "+2 Hide in non-open areas", "LA –1"] },
  // ── Planar Handbook races
  { cat: "Planar Races", name: "Buomman", la: 0, rhd: 0, rhdType: 8, bonuses: { wis: 2, cha: -2 }, traits: ["Medium humanoid (buomman, extraplanar)", "Naturally psionic (2 bonus PP)", "Sound mimicry at will", "+2 Concentration/Sense Motive", "Favored class: Monk"] },
  { cat: "Planar Races", name: "Mephling, Air", la: 0, rhd: 0, rhdType: 8, bonuses: { dex: 4, str: -2, con: -2 }, traits: ["Small outsider (air, extraplanar)", "Fly speed 20 ft (perfect)", "Immune: electricity", "Breath weapon: 15-ft cone of cold air (1d4 cold) 1/day", "Low-light vision", "Favored class: Rogue"] },
  { cat: "Planar Races", name: "Mephling, Fire", la: 0, rhd: 0, rhdType: 8, bonuses: { dex: 2, int: 2, con: -2 }, traits: ["Small outsider (fire, extraplanar)", "Fire resistance 5", "Breath weapon: 15-ft cone fire (1d4) 1/day", "Darkvision 60 ft", "Favored class: Sorcerer"] },
  { cat: "Planar Races", name: "Mephling, Earth", la: 0, rhd: 0, rhdType: 8, bonuses: { str: 2, con: 2, dex: -2 }, traits: ["Small outsider (earth, extraplanar)", "DR 2/magic", "Breath weapon: 15-ft cone of grit (1d4) 1/day", "Darkvision 60 ft", "Favored class: Fighter"] },
  { cat: "Planar Races", name: "Mephling, Water", la: 0, rhd: 0, rhdType: 8, bonuses: { dex: 2, con: 2, cha: -2 }, traits: ["Small outsider (water, extraplanar)", "Swim speed 40 ft", "Breath weapon: 15-ft cone of caustic liquid (1d4) 1/day", "Darkvision 60 ft", "Favored class: Druid"] },
  { cat: "Planar Races", name: "Shadowswyft", la: 1, rhd: 0, rhdType: 8, bonuses: { dex: 4, con: -2, cha: 2 }, traits: ["Medium outsider (shadow, extraplanar)", "Hide in Plain Sight (shadowy areas)", "Darkvision 60 ft", "Shadow Blend (50% miss in anything less than full daylight)", "LA +1"] },
  { cat: "Planar Races", name: "Spiker", la: 0, rhd: 0, rhdType: 8, bonuses: { str: 2, dex: -2 }, traits: ["Medium humanoid (extraplanar)", "Detachable spikes (thrown as javelins, regrow in 24h)", "+2 natural armor", "Darkvision 60 ft", "Favored class: Barbarian"] },
  { cat: "Planar Races", name: "Wildren", la: 0, rhd: 0, rhdType: 8, bonuses: { con: 2, wis: 2, cha: -4 }, traits: ["Small humanoid (dwarf-kin, celestial)", "Burrow speed 20 ft", "Low-light vision", "Scent", "+2 natural armor", "Favored class: Ranger"] },
  // ── Oriental Adventures / Rokugan
  { cat: "Oriental Adventures", name: "Hengeyokai", la: 0, rhd: 0, rhdType: 8, bonuses: {}, traits: ["Medium humanoid (shapechanger)", "Alternate Form: animal/hybrid/human (3 forms)", "Low-light vision", "+2 racial bonus on Wilderness Lore/Handle Animal", "Favored class: Shaman or Sorcerer"] },
  { cat: "Oriental Adventures", name: "Korobokuru", la: 0, rhd: 0, rhdType: 8, bonuses: { con: 2, wis: 2, cha: -4 }, traits: ["Small humanoid (dwarf-kin)", "Mountain Movement", "Stonecunning", "Low-light vision", "Favored class: Fighter"] },
  { cat: "Oriental Adventures", name: "Nezumi (Ratfolk)", la: 0, rhd: 0, rhdType: 8, bonuses: { con: 2, cha: -2 }, traits: ["Medium humanoid (nezumi)", "Speed 40 ft", "Scent", "Low-light vision", "+4 racial bonus Move Silently", "Favored class: Rogue"] },
  { cat: "Oriental Adventures", name: "Spirit Folk (River)", la: 0, rhd: 0, rhdType: 8, bonuses: {}, traits: ["Medium humanoid (spirit folk)", "Swim speed 30 ft", "Water breathing", "Favored class: Shaman"] },
  { cat: "Oriental Adventures", name: "Spirit Folk (Sea)", la: 0, rhd: 0, rhdType: 8, bonuses: {}, traits: ["Medium humanoid (spirit folk)", "Swim speed 40 ft", "Breathe water and air", "Speak with fish at will", "Favored class: Shaman"] },
  { cat: "Oriental Adventures", name: "Spirit Folk (Mountain)", la: 0, rhd: 0, rhdType: 8, bonuses: {}, traits: ["Medium humanoid (spirit folk)", "Speed 40 ft on slopes", "Pass without trace (mountains only) at will", "Favored class: Shaman"] },
  { cat: "Oriental Adventures", name: "Vanara", la: 0, rhd: 0, rhdType: 8, bonuses: { dex: 2, int: 2, wis: -2, cha: -2 }, traits: ["Medium humanoid (vanara)", "Prehensile tail (can hold light object, not attack)", "+4 Climb/Balance", "Low-light vision", "Favored class: Monk or Sorcerer"] },
  // ── Sandstorm / Frostburn / Stormwrack
  { cat: "Elemental Environments", name: "Asherati", la: 0, rhd: 0, rhdType: 8, bonuses: {}, traits: ["Medium humanoid (asherati)", "Sandswim: burrow through sand at speed 20 ft", "Body Lamp: shed light as torch at will", "Favored class: Rogue"] },
  { cat: "Elemental Environments", name: "Bhuka", la: 0, rhd: 0, rhdType: 8, bonuses: { dex: 2, wis: 2, con: -2, cha: -2 }, traits: ["Small humanoid (bhuka)", "Speed 30 ft", "Darkvision 60 ft", "Waste Strider: no penalties in desert terrain", "+4 Survival in desert", "Favored class: Ranger"] },
  { cat: "Elemental Environments", name: "Lumi", la: 0, rhd: 0, rhdType: 8, bonuses: { int: 2, wis: 2, cha: 2, str: -2, con: -2 }, traits: ["Medium outsider (extraplanar, positive energy)", "Shed light as candle at will", "Positive energy affinity (healed by positive, harmed by negative)", "Lucent Lance 1/day (ray 3d6 vs undead)", "Darkvision 60 ft", "Favored class: Cleric"] },
  { cat: "Elemental Environments", name: "Frostblood Half-Orc", la: 0, rhd: 0, rhdType: 8, bonuses: { str: 4, int: -2, wis: -2, cha: -2 }, traits: ["Medium humanoid (orc, dragonblood)", "Darkvision 60 ft", "Cold resistance 5", "Light sensitivity (as orc)", "Favored class: Barbarian"] },
  // ── Eberron additional
  { cat: "Eberron Races", name: "Quori (Inspired)", la: 2, rhd: 0, rhdType: 8, bonuses: { int: 2, wis: 2, cha: 2, con: -2 }, traits: ["Medium humanoid (psionic, quori-touched)", "Naturally psionic (3 bonus PP)", "Mind Seed: quori dream-control", "Mind Blank 1/day", "+2 Bluff/Diplomacy", "Darkvision 60 ft", "LA +2"] },
  { cat: "Eberron Races", name: "Warforged Scout (Small)", la: 0, rhd: 0, rhdType: 8, bonuses: { dex: 4, con: 2, wis: -2, cha: -4 }, traits: ["Small living construct", "Immune: poison/disease/sleep/paralysis", "No need to eat/drink/breathe", "Natural armor +2", "Speed 20 ft", "Favored class: Rogue"] },
  // ── Savage Species anthropomorphic
  { cat: "Anthropomorphic", name: "Anthropomorphic Ape", la: 2, rhd: 4, rhdType: 8, bonuses: { str: 8, dex: 2, con: 4, int: -4, cha: -4 }, traits: ["Medium animal (anthropomorphic)", "4d8 racial HD", "Low-light vision", "Scent", "Climb speed 30 ft", "Natural weapons: 2 slams (1d6)", "LA +2"] },
  { cat: "Anthropomorphic", name: "Anthropomorphic Bat", la: 0, rhd: 0, rhdType: 8, bonuses: { str: -4, wis: 6, cha: -2 }, traits: ["Small monstrous humanoid", "Fly 20 ft (average)", "Blindsense 20 ft", "Low-light vision", "Favored class: Druid"] },
  { cat: "Anthropomorphic", name: "Anthropomorphic Lizard", la: 0, rhd: 0, rhdType: 8, bonuses: { str: -4, dex: 2, wis: 4, cha: -4 }, traits: ["Small monstrous humanoid", "Natural armor +1", "Swim speed 20 ft", "Hold breath", "+4 Hide in natural settings", "Favored class: Druid"] },
  { cat: "Anthropomorphic", name: "Anthropomorphic Monkey", la: 0, rhd: 0, rhdType: 8, bonuses: { str: -4, dex: 2, wis: 4, cha: -2 }, traits: ["Small monstrous humanoid", "Climb speed 30 ft", "Prehensile tail", "+8 Climb", "Low-light vision", "Favored class: Druid"] },
  // ── Additional Monster Manual I playable
  { cat: "Monstrous Humanoids", name: "Ogre Mage (Lesser)", la: 4, rhd: 5, rhdType: 8, bonuses: { str: 8, con: 4, int: 2, cha: 4, wis: 2, dex: 0 }, traits: ["Large giant (oni)", "5d8 racial HD", "Darkvision 60 ft", "Natural armor +5", "Flight 40 ft (good)", "Spell-like: Cone of Cold/Darkness/Gaseous Form/Invisibility/Sleep 1/day each", "Regeneration 5", "LA +4"] },
  { cat: "Monstrous Humanoids", name: "Lycanthrope, Werebear", la: 4, rhd: 0, rhdType: 8, bonuses: { str: 8, con: 6, wis: 2, dex: -2 }, traits: ["Medium humanoid (shapechanger)", "Bear or hybrid alternate form", "DR 10/silver in animal/hybrid form", "Scent", "Low-light vision", "Infected lycanthropy on injury", "Natural weapons: 2 claws (1d8) + bite (2d6) in hybrid/bear", "LA +4"] },
  { cat: "Monstrous Humanoids", name: "Lycanthrope, Wererat", la: 2, rhd: 0, rhdType: 8, bonuses: { dex: 6, con: 2, int: 2 }, traits: ["Medium humanoid (shapechanger)", "Rat or hybrid alternate form", "DR 5/silver", "Scent", "Low-light vision", "Infected lycanthropy (injury)", "LA +2"] },
  { cat: "Monstrous Humanoids", name: "Lycanthrope, Wereboar", la: 2, rhd: 0, rhdType: 8, bonuses: { str: 4, con: 6, wis: 2, dex: -2 }, traits: ["Medium humanoid (shapechanger)", "Boar or hybrid alternate form", "DR 10/silver", "Scent", "Low-light vision", "Infected lycanthropy (injury)", "LA +2"] },
  { cat: "Monstrous Humanoids", name: "Gnoll, Flinds", la: 2, rhd: 2, rhdType: 8, bonuses: { str: 6, con: 2, int: -2, cha: -2 }, traits: ["Medium humanoid (gnoll)", "2d8 racial HD", "Darkvision 60 ft", "Natural armor +2", "Flindbar proficiency (triple flail, may disarm on hit)", "LA +2"] },
  { cat: "Monstrous Humanoids", name: "Kenku", la: 0, rhd: 0, rhdType: 8, bonuses: { dex: 2, str: -2 }, traits: ["Medium humanoid (kenku)", "Low-light vision", "Mimicry: can mimic sounds/voices heard", "Natural weapons: 2 claws (1d3) OR weapon", "Favored class: Rogue"] },
  { cat: "Monstrous Humanoids", name: "Doppelganger", la: 4, rhd: 4, rhdType: 8, bonuses: { dex: 4, cha: 4, int: 2 }, traits: ["Medium monstrous humanoid (shapechanger)", "4d8 racial HD", "Darkvision 60 ft", "Detect Thoughts at will (disguise self)", "Alternate Form: copy any humanoid shape", "Natural armor +4", "LA +4"] },
  { cat: "Monstrous Humanoids", name: "Werewolf (Afflicted)", la: 2, rhd: 0, rhdType: 8, bonuses: { str: 2, dex: 4, con: 4 }, traits: ["Medium humanoid (shapechanger)", "Wolf or hybrid form", "DR 5/silver (afflicted)", "Scent", "Low-light vision", "Infected lycanthropy", "LA +2"] },
  // ── Forgotten Realms / FRCS
  { cat: "Forgotten Realms", name: "Aasimar (Lesser)", la: 0, rhd: 0, rhdType: 8, bonuses: { wis: 2, cha: 2 }, traits: ["Medium humanoid (planetouched)", "Darkvision 60 ft", "Light spell-like 1/day", "Resist acid/cold/electricity 5", "Player's Guide to Faerûn variant (no LA)"] },
  { cat: "Forgotten Realms", name: "Tiefling (Lesser)", la: 0, rhd: 0, rhdType: 8, bonuses: { int: 2, dex: 2, cha: -2 }, traits: ["Medium humanoid (planetouched)", "Darkvision 60 ft", "Darkness 1/day", "Resist cold/fire/electricity 5", "Player's Guide to Faerûn variant (no LA)"] },
  { cat: "Forgotten Realms", name: "Air Genasi (Lesser)", la: 0, rhd: 0, rhdType: 8, bonuses: { dex: 2, int: 2, wis: -2, cha: -2 }, traits: ["Medium humanoid (planetouched)", "Darkvision 60 ft", "Levitate 1/day", "Player's Guide to Faerûn (LA +0 variant)"] },
  { cat: "Forgotten Realms", name: "Elf, Star (Selu'taar)", la: 0, rhd: 0, rhdType: 8, bonuses: { dex: 2, con: -2, int: 2, wis: 2, cha: -2 }, traits: ["Medium humanoid (elf)", "Low-light vision", "Immune: magic sleep", "+2 Knowledge checks", "Speak with Stars (comprehend languages 1/day)", "Favored class: Wizard"] },
  { cat: "Forgotten Realms", name: "Elf, Lythari (Ghostwalk)", la: 2, rhd: 0, rhdType: 8, bonuses: { dex: 2, wis: 2 }, traits: ["Medium humanoid (elf, shapechanger)", "Lycanthropic elf", "Natural lycanthrope: wolf form", "Low-light vision", "Immune: sleep", "LA +2"] },
  { cat: "Forgotten Realms", name: "Elf, Deep (Ssri-Tel'Quessir)", la: 0, rhd: 0, rhdType: 8, bonuses: { dex: 2, con: -2, int: 2 }, traits: ["Medium humanoid (elf)", "Darkvision 60 ft", "Low-light vision", "Immune: sleep", "+2 Listen/Search/Spot", "Favored class: Wizard"] },
  { cat: "Forgotten Realms", name: "Half-Drow", la: 0, rhd: 0, rhdType: 8, bonuses: { dex: 2, con: -2 }, traits: ["Medium humanoid (elf)", "Darkvision 30 ft", "Low-light vision", "Immune: sleep", "+1 Listen/Search/Spot", "Elven blood and drow blood", "Favored class: Any"] },
  { cat: "Forgotten Realms", name: "Krinth (half-shade)", la: 0, rhd: 0, rhdType: 8, bonuses: { con: 2, cha: -2 }, traits: ["Medium humanoid (krinth)", "Darkvision 60 ft", "Cold resistance 5", "Shadowy form: +2 Hide in darkness", "Champions of Ruin variant", "Favored class: Fighter"] },
  { cat: "Forgotten Realms", name: "Lupin", la: 0, rhd: 0, rhdType: 8, bonuses: {}, traits: ["Medium monstrous humanoid (lupin)", "Scent", "Low-light vision", "Howl (sonic, Will DC or shaken)", "+4 Survival/Sense Motive", "Dragon Compendium variant", "Favored class: Ranger"] },
]

const RACE_PHYSICAL = {
  "Human": { size: "Medium", height: [4, 8, 6, 2], weight: [100, 250], age: [15, 35, 53, 70] },
  "Half-Elf": { size: "Medium", height: [4, 9, 6, 2], weight: [100, 180], age: [20, 62, 93, 125] },
  "Half-Orc": { size: "Medium", height: [4, 10, 6, 4], weight: [150, 280], age: [14, 30, 45, 60] },
  "Elf, High": { size: "Medium", height: [4, 5, 5, 5], weight: [85, 135], age: [110, 175, 263, 350] },
  "Elf, Grey": { size: "Medium", height: [4, 5, 5, 5], weight: [80, 130], age: [110, 175, 263, 350] },
  "Elf, Wood": { size: "Medium", height: [4, 6, 5, 6], weight: [85, 140], age: [110, 175, 263, 350] },
  "Elf, Wild": { size: "Medium", height: [4, 6, 5, 6], weight: [85, 140], age: [110, 175, 263, 350] },
  "Elf, Sun (Gold)": { size: "Medium", height: [4, 5, 5, 5], weight: [80, 130], age: [110, 175, 263, 350] },
  "Elf, Moon (Silver)": { size: "Medium", height: [4, 5, 5, 5], weight: [80, 130], age: [110, 175, 263, 350] },
  "Elf, Sea": { size: "Medium", height: [4, 6, 5, 8], weight: [90, 150], age: [110, 175, 263, 350] },
  "Elf, Snow": { size: "Medium", height: [4, 5, 5, 5], weight: [80, 125], age: [110, 175, 263, 350] },
  "Drow (Dark Elf)": { size: "Medium", height: [4, 4, 5, 4], weight: [80, 120], age: [110, 175, 263, 350] },
  "Avariel (Winged Elf)": { size: "Medium", height: [4, 5, 5, 5], weight: [75, 115], age: [110, 175, 263, 350] },
  "Dwarf, Hill": { size: "Medium", height: [3, 9, 4, 5], weight: [130, 200], age: [40, 125, 188, 250] },
  "Dwarf, Mountain": { size: "Medium", height: [3, 9, 4, 5], weight: [140, 210], age: [40, 125, 188, 250] },
  "Duergar": { size: "Medium", height: [3, 9, 4, 5], weight: [130, 200], age: [40, 125, 188, 250] },
  "Halfling, Lightfoot": { size: "Small", height: [2, 8, 3, 4], weight: [30, 50], age: [20, 50, 75, 100] },
  "Halfling, Tallfellow": { size: "Small", height: [3, 0, 3, 8], weight: [35, 55], age: [20, 50, 75, 100] },
  "Halfling, Deep": { size: "Small", height: [2, 8, 3, 4], weight: [28, 48], age: [20, 50, 75, 100] },
  "Gnome, Rock": { size: "Small", height: [3, 0, 3, 8], weight: [40, 55], age: [40, 100, 150, 200] },
  "Gnome, Forest": { size: "Small", height: [2, 10, 3, 6], weight: [35, 50], age: [40, 100, 150, 200] },
  "Svirfneblin (Deep Gnome)": { size: "Small", height: [3, 0, 3, 6], weight: [40, 50], age: [40, 100, 150, 200] },
  "Aasimar": { size: "Medium", height: [4, 8, 6, 2], weight: [100, 250], age: [15, 35, 53, 70] },
  "Tiefling": { size: "Medium", height: [4, 8, 6, 2], weight: [100, 250], age: [15, 35, 53, 70] },
  "Air Genasi": { size: "Medium", height: [4, 8, 6, 2], weight: [100, 200], age: [15, 35, 53, 70] },
  "Earth Genasi": { size: "Medium", height: [4, 8, 6, 2], weight: [120, 240], age: [15, 35, 53, 70] },
  "Fire Genasi": { size: "Medium", height: [4, 8, 6, 2], weight: [100, 200], age: [15, 35, 53, 70] },
  "Water Genasi": { size: "Medium", height: [4, 8, 6, 2], weight: [100, 200], age: [15, 35, 53, 70] },
  "Orc": { size: "Medium", height: [5, 1, 6, 4], weight: [180, 280], age: [12, 25, 38, 50] },
  "Bugbear": { size: "Medium", height: [5, 0, 6, 4], weight: [250, 400], age: [12, 30, 45, 60] },
  "Gnoll": { size: "Medium", height: [6, 0, 7, 2], weight: [280, 360], age: [12, 30, 45, 60] },
  "Hobgoblin": { size: "Medium", height: [4, 8, 5, 8], weight: [150, 220], age: [14, 30, 45, 60] },
  "Kobold": { size: "Small", height: [2, 0, 2, 6], weight: [25, 35], age: [6, 20, 40, 60] },
  "Lizardfolk": { size: "Medium", height: [5, 0, 6, 6], weight: [200, 300], age: [12, 30, 45, 60] },
  "Goblin": { size: "Small", height: [3, 0, 3, 8], weight: [40, 60], age: [10, 20, 35, 50] },
  "Ogre": { size: "Large", height: [9, 0, 11, 0], weight: [600, 1000], age: [15, 40, 60, 80] },
  "Troll (Lesser)": { size: "Large", height: [8, 0, 10, 0], weight: [500, 800], age: [10, 25, 38, 50] },
  "Minotaur": { size: "Large", height: [7, 0, 8, 6], weight: [700, 900], age: [15, 35, 53, 70] },
  "Centaur": { size: "Large", height: [7, 0, 8, 0], weight: [2100, 2400], age: [15, 45, 68, 90] },
  "Harpy": { size: "Medium", height: [5, 0, 6, 0], weight: [100, 160], age: [15, 30, 45, 60] },
  "Satyr": { size: "Medium", height: [4, 6, 5, 6], weight: [130, 200], age: [15, 40, 65, 90] },
  "Warforged": { size: "Medium", height: [5, 0, 6, 6], weight: [270, 310], age: [2, 30, 50, 100] },
  "Githzerai": { size: "Medium", height: [5, 0, 6, 6], weight: [100, 190], age: [15, 60, 90, 120] },
  "Githyanki": { size: "Medium", height: [5, 0, 6, 6], weight: [100, 190], age: [15, 60, 90, 120] },
  "Thri-Kreen": { size: "Medium", height: [5, 0, 6, 6], weight: [400, 450], age: [5, 17, 28, 35] },
  "Dragonborn": { size: "Medium", height: [5, 6, 6, 6], weight: [220, 320], age: [15, 35, 53, 70] },
  "Half-Dragon (Chromatic)": { size: "Medium", height: [5, 6, 7, 0], weight: [200, 350], age: [15, 35, 53, 70] },
  "Half-Dragon (Metallic)": { size: "Medium", height: [5, 6, 7, 0], weight: [200, 350], age: [15, 35, 53, 70] },
}
