// ─────────────────────────────────────────────────────────────────────────
// D&D 3.5 Gestalt Character Creator — Spells & Powers Data File
// Edit this file to add, modify or remove spells and psionic powers.
// Used only for the Browse & Restrict panel — not exhaustive.
// ─────────────────────────────────────────────────────────────────────────

// ─── SPELL REFERENCE LIBRARY ─────────────────────────────────────────────────
// Each entry: {name, school, level, classes:[...]}
const SPELL_LIBRARY = [
  // 0th level
  {name:"Acid Splash",school:"Conjuration",level:0,classes:["Sorcerer","Wizard"]},
  {name:"Dancing Lights",school:"Evocation",level:0,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Daze",school:"Enchantment",level:0,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Detect Magic",school:"Divination",level:0,classes:["Bard","Cleric","Druid","Sorcerer","Wizard"]},
  {name:"Detect Poison",school:"Divination",level:0,classes:["Cleric","Druid","Paladin","Ranger","Sorcerer","Wizard"]},
  {name:"Disrupt Undead",school:"Necromancy",level:0,classes:["Sorcerer","Wizard"]},
  {name:"Flare",school:"Evocation",level:0,classes:["Bard","Druid","Sorcerer","Wizard"]},
  {name:"Ghost Sound",school:"Illusion",level:0,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Know Direction",school:"Divination",level:0,classes:["Bard","Druid"]},
  {name:"Light",school:"Evocation",level:0,classes:["Bard","Cleric","Druid","Sorcerer","Wizard"]},
  {name:"Mage Hand",school:"Transmutation",level:0,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Mending",school:"Transmutation",level:0,classes:["Bard","Cleric","Druid","Sorcerer","Wizard"]},
  {name:"Message",school:"Transmutation",level:0,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Open/Close",school:"Transmutation",level:0,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Prestidigitation",school:"Universal",level:0,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Ray of Frost",school:"Conjuration",level:0,classes:["Sorcerer","Wizard"]},
  {name:"Read Magic",school:"Divination",level:0,classes:["Bard","Cleric","Druid","Paladin","Ranger","Sorcerer","Wizard"]},
  {name:"Resistance",school:"Abjuration",level:0,classes:["Bard","Cleric","Druid","Paladin","Sorcerer","Wizard"]},
  {name:"Virtue",school:"Transmutation",level:0,classes:["Cleric","Druid","Paladin"]},
  // 1st level
  {name:"Alarm",school:"Abjuration",level:1,classes:["Ranger","Sorcerer","Wizard"]},
  {name:"Animate Rope",school:"Transmutation",level:1,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Burning Hands",school:"Evocation",level:1,classes:["Sorcerer","Wizard"]},
  {name:"Cause Fear",school:"Necromancy",level:1,classes:["Bard","Cleric","Sorcerer","Wizard"]},
  {name:"Charm Person",school:"Enchantment",level:1,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Chill Touch",school:"Necromancy",level:1,classes:["Sorcerer","Wizard"]},
  {name:"Color Spray",school:"Illusion",level:1,classes:["Sorcerer","Wizard"]},
  {name:"Comprehend Languages",school:"Divination",level:1,classes:["Bard","Cleric","Sorcerer","Wizard"]},
  {name:"Cure Light Wounds",school:"Conjuration",level:1,classes:["Bard","Cleric","Druid","Paladin","Ranger"]},
  {name:"Detect Secret Doors",school:"Divination",level:1,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Disguise Self",school:"Illusion",level:1,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Endure Elements",school:"Abjuration",level:1,classes:["Cleric","Druid","Paladin","Ranger","Sorcerer","Wizard"]},
  {name:"Entangle",school:"Transmutation",level:1,classes:["Druid","Ranger"]},
  {name:"Enlarge Person",school:"Transmutation",level:1,classes:["Sorcerer","Wizard"]},
  {name:"Expeditious Retreat",school:"Transmutation",level:1,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Feather Fall",school:"Transmutation",level:1,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Goodberry",school:"Transmutation",level:1,classes:["Druid","Ranger"]},
  {name:"Grease",school:"Conjuration",level:1,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Hypnotism",school:"Enchantment",level:1,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Identify",school:"Divination",level:1,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Inflict Light Wounds",school:"Necromancy",level:1,classes:["Cleric"]},
  {name:"Invisibility to Animals",school:"Abjuration",level:1,classes:["Druid","Ranger"]},
  {name:"Jump",school:"Transmutation",level:1,classes:["Druid","Ranger","Sorcerer","Wizard"]},
  {name:"Longstrider",school:"Transmutation",level:1,classes:["Druid","Ranger"]},
  {name:"Magic Missile",school:"Evocation",level:1,classes:["Sorcerer","Wizard"]},
  {name:"Mage Armor",school:"Conjuration",level:1,classes:["Sorcerer","Wizard"]},
  {name:"Mount",school:"Conjuration",level:1,classes:["Sorcerer","Wizard"]},
  {name:"Obscuring Mist",school:"Conjuration",level:1,classes:["Cleric","Druid","Sorcerer","Wizard"]},
  {name:"Protection from Chaos",school:"Abjuration",level:1,classes:["Cleric","Paladin","Sorcerer","Wizard"]},
  {name:"Protection from Evil",school:"Abjuration",level:1,classes:["Cleric","Paladin","Sorcerer","Wizard"]},
  {name:"Protection from Good",school:"Abjuration",level:1,classes:["Cleric","Sorcerer","Wizard"]},
  {name:"Protection from Law",school:"Abjuration",level:1,classes:["Cleric","Sorcerer","Wizard"]},
  {name:"Ray of Enfeeblement",school:"Necromancy",level:1,classes:["Sorcerer","Wizard"]},
  {name:"Reduce Person",school:"Transmutation",level:1,classes:["Sorcerer","Wizard"]},
  {name:"Shield",school:"Abjuration",level:1,classes:["Sorcerer","Wizard"]},
  {name:"Shocking Grasp",school:"Evocation",level:1,classes:["Sorcerer","Wizard"]},
  {name:"Silent Image",school:"Illusion",level:1,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Sleep",school:"Enchantment",level:1,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Summon Monster I",school:"Conjuration",level:1,classes:["Bard","Cleric","Sorcerer","Wizard"]},
  {name:"Tenser's Floating Disk",school:"Evocation",level:1,classes:["Sorcerer","Wizard"]},
  {name:"True Strike",school:"Divination",level:1,classes:["Sorcerer","Wizard"]},
  {name:"Unseen Servant",school:"Conjuration",level:1,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Ventriloquism",school:"Illusion",level:1,classes:["Bard","Sorcerer","Wizard"]},
  // 2nd level
  {name:"Acid Arrow",school:"Conjuration",level:2,classes:["Sorcerer","Wizard"]},
  {name:"Alter Self",school:"Transmutation",level:2,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Animal Messenger",school:"Enchantment",level:2,classes:["Bard","Druid","Ranger"]},
  {name:"Arcane Lock",school:"Abjuration",level:2,classes:["Sorcerer","Wizard"]},
  {name:"Barkskin",school:"Transmutation",level:2,classes:["Druid","Ranger"]},
  {name:"Bear's Endurance",school:"Transmutation",level:2,classes:["Cleric","Druid","Ranger","Sorcerer","Wizard"]},
  {name:"Blindness/Deafness",school:"Necromancy",level:2,classes:["Bard","Cleric","Sorcerer","Wizard"]},
  {name:"Blur",school:"Illusion",level:2,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Bull's Strength",school:"Transmutation",level:2,classes:["Cleric","Druid","Paladin","Sorcerer","Wizard"]},
  {name:"Cat's Grace",school:"Transmutation",level:2,classes:["Bard","Druid","Ranger","Sorcerer","Wizard"]},
  {name:"Command Undead",school:"Necromancy",level:2,classes:["Sorcerer","Wizard"]},
  {name:"Cure Moderate Wounds",school:"Conjuration",level:2,classes:["Bard","Cleric","Druid","Paladin","Ranger"]},
  {name:"Darkness",school:"Evocation",level:2,classes:["Bard","Cleric","Sorcerer","Wizard"]},
  {name:"Darkvision",school:"Transmutation",level:2,classes:["Ranger","Sorcerer","Wizard"]},
  {name:"Detect Thoughts",school:"Divination",level:2,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Eagle's Splendor",school:"Transmutation",level:2,classes:["Bard","Cleric","Paladin","Sorcerer","Wizard"]},
  {name:"False Life",school:"Necromancy",level:2,classes:["Sorcerer","Wizard"]},
  {name:"Flaming Sphere",school:"Evocation",level:2,classes:["Druid","Sorcerer","Wizard"]},
  {name:"Fog Cloud",school:"Conjuration",level:2,classes:["Druid","Ranger","Sorcerer","Wizard"]},
  {name:"Fox's Cunning",school:"Transmutation",level:2,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Ghoul Touch",school:"Necromancy",level:2,classes:["Sorcerer","Wizard"]},
  {name:"Glitterdust",school:"Conjuration",level:2,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Hold Person",school:"Enchantment",level:2,classes:["Bard","Cleric","Sorcerer","Wizard"]},
  {name:"Hypnotic Pattern",school:"Illusion",level:2,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Invisibility",school:"Illusion",level:2,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Knock",school:"Transmutation",level:2,classes:["Sorcerer","Wizard"]},
  {name:"Levitate",school:"Transmutation",level:2,classes:["Sorcerer","Wizard"]},
  {name:"Locate Object",school:"Divination",level:2,classes:["Bard","Cleric","Sorcerer","Wizard"]},
  {name:"Mirror Image",school:"Illusion",level:2,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Misdirection",school:"Illusion",level:2,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Owl's Wisdom",school:"Transmutation",level:2,classes:["Cleric","Druid","Paladin","Ranger","Sorcerer","Wizard"]},
  {name:"Resist Energy",school:"Abjuration",level:2,classes:["Cleric","Druid","Paladin","Ranger","Sorcerer","Wizard"]},
  {name:"Rope Trick",school:"Transmutation",level:2,classes:["Sorcerer","Wizard"]},
  {name:"Scorching Ray",school:"Evocation",level:2,classes:["Sorcerer","Wizard"]},
  {name:"See Invisibility",school:"Divination",level:2,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Shatter",school:"Evocation",level:2,classes:["Bard","Cleric","Sorcerer","Wizard"]},
  {name:"Silence",school:"Illusion",level:2,classes:["Bard","Cleric"]},
  {name:"Sound Burst",school:"Evocation",level:2,classes:["Bard","Cleric"]},
  {name:"Spectral Hand",school:"Necromancy",level:2,classes:["Sorcerer","Wizard"]},
  {name:"Spider Climb",school:"Transmutation",level:2,classes:["Druid","Sorcerer","Wizard"]},
  {name:"Summon Monster II",school:"Conjuration",level:2,classes:["Bard","Cleric","Sorcerer","Wizard"]},
  {name:"Summon Swarm",school:"Conjuration",level:2,classes:["Bard","Druid","Sorcerer","Wizard"]},
  {name:"Touch of Idiocy",school:"Enchantment",level:2,classes:["Sorcerer","Wizard"]},
  {name:"Web",school:"Conjuration",level:2,classes:["Sorcerer","Wizard"]},
  {name:"Whispering Wind",school:"Transmutation",level:2,classes:["Bard","Sorcerer","Wizard"]},
  // 3rd level
  {name:"Arcane Sight",school:"Divination",level:3,classes:["Sorcerer","Wizard"]},
  {name:"Blink",school:"Transmutation",level:3,classes:["Sorcerer","Wizard"]},
  {name:"Call Lightning",school:"Evocation",level:3,classes:["Druid"]},
  {name:"Clairaudience/Clairvoyance",school:"Divination",level:3,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Contagion",school:"Necromancy",level:3,classes:["Cleric","Druid","Sorcerer","Wizard"]},
  {name:"Create Food and Water",school:"Conjuration",level:3,classes:["Cleric"]},
  {name:"Cure Serious Wounds",school:"Conjuration",level:3,classes:["Bard","Cleric","Druid","Ranger"]},
  {name:"Daylight",school:"Evocation",level:3,classes:["Bard","Cleric","Druid","Paladin","Sorcerer","Wizard"]},
  {name:"Deep Slumber",school:"Enchantment",level:3,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Displacement",school:"Illusion",level:3,classes:["Sorcerer","Wizard"]},
  {name:"Dispel Magic",school:"Abjuration",level:3,classes:["Bard","Cleric","Druid","Paladin","Sorcerer","Wizard"]},
  {name:"Explosive Runes",school:"Abjuration",level:3,classes:["Sorcerer","Wizard"]},
  {name:"Fireball",school:"Evocation",level:3,classes:["Sorcerer","Wizard"]},
  {name:"Flame Arrow",school:"Transmutation",level:3,classes:["Ranger","Sorcerer","Wizard"]},
  {name:"Fly",school:"Transmutation",level:3,classes:["Sorcerer","Wizard"]},
  {name:"Gaseous Form",school:"Transmutation",level:3,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Gentle Repose",school:"Necromancy",level:3,classes:["Cleric","Sorcerer","Wizard"]},
  {name:"Halt Undead",school:"Necromancy",level:3,classes:["Sorcerer","Wizard"]},
  {name:"Haste",school:"Transmutation",level:3,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Heroism",school:"Enchantment",level:3,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Hold Animal",school:"Enchantment",level:3,classes:["Druid","Ranger"]},
  {name:"Hold Person",school:"Enchantment",level:3,classes:["Cleric"]},
  {name:"Invisibility Sphere",school:"Illusion",level:3,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Keen Edge",school:"Transmutation",level:3,classes:["Sorcerer","Wizard"]},
  {name:"Lightning Bolt",school:"Evocation",level:3,classes:["Sorcerer","Wizard"]},
  {name:"Magic Circle vs. Evil",school:"Abjuration",level:3,classes:["Cleric","Paladin","Sorcerer","Wizard"]},
  {name:"Major Image",school:"Illusion",level:3,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Nondetection",school:"Abjuration",level:3,classes:["Ranger","Sorcerer","Wizard"]},
  {name:"Phantom Steed",school:"Conjuration",level:3,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Poison",school:"Necromancy",level:3,classes:["Cleric","Druid"]},
  {name:"Protection from Energy",school:"Abjuration",level:3,classes:["Cleric","Druid","Ranger","Sorcerer","Wizard"]},
  {name:"Rage",school:"Enchantment",level:3,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Ray of Exhaustion",school:"Necromancy",level:3,classes:["Sorcerer","Wizard"]},
  {name:"Remove Blindness/Deafness",school:"Conjuration",level:3,classes:["Cleric","Paladin"]},
  {name:"Remove Curse",school:"Abjuration",level:3,classes:["Bard","Cleric","Paladin","Sorcerer","Wizard"]},
  {name:"Remove Disease",school:"Conjuration",level:3,classes:["Cleric","Druid","Ranger"]},
  {name:"Shrink Item",school:"Transmutation",level:3,classes:["Sorcerer","Wizard"]},
  {name:"Slow",school:"Transmutation",level:3,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Sleet Storm",school:"Conjuration",level:3,classes:["Druid","Sorcerer","Wizard"]},
  {name:"Stinking Cloud",school:"Conjuration",level:3,classes:["Sorcerer","Wizard"]},
  {name:"Suggestion",school:"Enchantment",level:3,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Summon Monster III",school:"Conjuration",level:3,classes:["Bard","Cleric","Sorcerer","Wizard"]},
  {name:"Tongues",school:"Divination",level:3,classes:["Bard","Cleric","Sorcerer","Wizard"]},
  {name:"Vampiric Touch",school:"Necromancy",level:3,classes:["Sorcerer","Wizard"]},
  {name:"Water Breathing",school:"Transmutation",level:3,classes:["Cleric","Druid","Sorcerer","Wizard"]},
  {name:"Wind Wall",school:"Evocation",level:3,classes:["Cleric","Druid","Ranger","Sorcerer","Wizard"]},
  // 4th level
  {name:"Animate Dead",school:"Necromancy",level:4,classes:["Cleric","Sorcerer","Wizard"]},
  {name:"Arcane Eye",school:"Divination",level:4,classes:["Sorcerer","Wizard"]},
  {name:"Ball Lightning",school:"Evocation",level:4,classes:["Sorcerer","Wizard"]},
  {name:"Black Tentacles",school:"Conjuration",level:4,classes:["Sorcerer","Wizard"]},
  {name:"Charm Monster",school:"Enchantment",level:4,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Confusion",school:"Enchantment",level:4,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Contagion",school:"Necromancy",level:4,classes:["Sorcerer","Wizard"]},
  {name:"Cure Critical Wounds",school:"Conjuration",level:4,classes:["Cleric","Druid"]},
  {name:"Dimensional Anchor",school:"Abjuration",level:4,classes:["Cleric","Sorcerer","Wizard"]},
  {name:"Dimension Door",school:"Conjuration",level:4,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Dominate Person",school:"Enchantment",level:4,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Enervation",school:"Necromancy",level:4,classes:["Sorcerer","Wizard"]},
  {name:"Evard's Black Tentacles",school:"Conjuration",level:4,classes:["Sorcerer","Wizard"]},
  {name:"Fear",school:"Necromancy",level:4,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Fire Shield",school:"Evocation",level:4,classes:["Sorcerer","Wizard"]},
  {name:"Freedom of Movement",school:"Abjuration",level:4,classes:["Bard","Cleric","Druid","Ranger"]},
  {name:"Globe of Invulnerability (Lesser)",school:"Abjuration",level:4,classes:["Sorcerer","Wizard"]},
  {name:"Hallucinatory Terrain",school:"Illusion",level:4,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Ice Storm",school:"Evocation",level:4,classes:["Druid","Sorcerer","Wizard"]},
  {name:"Illusory Wall",school:"Illusion",level:4,classes:["Sorcerer","Wizard"]},
  {name:"Invisibility (Greater)",school:"Illusion",level:4,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Phantasmal Killer",school:"Illusion",level:4,classes:["Sorcerer","Wizard"]},
  {name:"Polymorph",school:"Transmutation",level:4,classes:["Sorcerer","Wizard"]},
  {name:"Remove Curse",school:"Abjuration",level:4,classes:["Sorcerer","Wizard"]},
  {name:"Resilient Sphere",school:"Evocation",level:4,classes:["Sorcerer","Wizard"]},
  {name:"Scrying",school:"Divination",level:4,classes:["Bard","Cleric","Druid","Sorcerer","Wizard"]},
  {name:"Shout",school:"Evocation",level:4,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Solid Fog",school:"Conjuration",level:4,classes:["Sorcerer","Wizard"]},
  {name:"Stone Shape",school:"Transmutation",level:4,classes:["Cleric","Druid","Sorcerer","Wizard"]},
  {name:"Stoneskin",school:"Abjuration",level:4,classes:["Druid","Sorcerer","Wizard"]},
  {name:"Summon Monster IV",school:"Conjuration",level:4,classes:["Bard","Cleric","Sorcerer","Wizard"]},
  {name:"Wall of Fire",school:"Evocation",level:4,classes:["Druid","Sorcerer","Wizard"]},
  {name:"Wall of Ice",school:"Evocation",level:4,classes:["Sorcerer","Wizard"]},
  // 5th level
  {name:"Animal Growth",school:"Transmutation",level:5,classes:["Druid","Ranger","Sorcerer","Wizard"]},
  {name:"Baleful Polymorph",school:"Transmutation",level:5,classes:["Druid","Sorcerer","Wizard"]},
  {name:"Break Enchantment",school:"Abjuration",level:5,classes:["Bard","Cleric","Paladin","Sorcerer","Wizard"]},
  {name:"Call Lightning Storm",school:"Evocation",level:5,classes:["Druid"]},
  {name:"Cloudkill",school:"Conjuration",level:5,classes:["Sorcerer","Wizard"]},
  {name:"Cone of Cold",school:"Evocation",level:5,classes:["Sorcerer","Wizard"]},
  {name:"Contact Other Plane",school:"Divination",level:5,classes:["Sorcerer","Wizard"]},
  {name:"Dominate Person",school:"Enchantment",level:5,classes:["Sorcerer","Wizard"]},
  {name:"Dream",school:"Illusion",level:5,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Fabricate",school:"Transmutation",level:5,classes:["Sorcerer","Wizard"]},
  {name:"False Vision",school:"Illusion",level:5,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Feeblemind",school:"Enchantment",level:5,classes:["Sorcerer","Wizard"]},
  {name:"Hold Monster",school:"Enchantment",level:5,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Interposing Hand",school:"Evocation",level:5,classes:["Sorcerer","Wizard"]},
  {name:"Mage's Faithful Hound",school:"Conjuration",level:5,classes:["Sorcerer","Wizard"]},
  {name:"Magic Jar",school:"Necromancy",level:5,classes:["Sorcerer","Wizard"]},
  {name:"Mind Fog",school:"Enchantment",level:5,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Mirage Arcana",school:"Illusion",level:5,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Nightmare",school:"Illusion",level:5,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Passwall",school:"Transmutation",level:5,classes:["Sorcerer","Wizard"]},
  {name:"Permanency",school:"Universal",level:5,classes:["Sorcerer","Wizard"]},
  {name:"Persistent Image",school:"Illusion",level:5,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Prying Eyes",school:"Divination",level:5,classes:["Sorcerer","Wizard"]},
  {name:"Raise Dead",school:"Conjuration",level:5,classes:["Cleric"]},
  {name:"Sending",school:"Evocation",level:5,classes:["Cleric","Sorcerer","Wizard"]},
  {name:"Shadow Evocation",school:"Illusion",level:5,classes:["Sorcerer","Wizard"]},
  {name:"Summon Monster V",school:"Conjuration",level:5,classes:["Bard","Cleric","Sorcerer","Wizard"]},
  {name:"Symbol of Pain",school:"Necromancy",level:5,classes:["Cleric","Sorcerer","Wizard"]},
  {name:"Symbol of Sleep",school:"Enchantment",level:5,classes:["Cleric","Sorcerer","Wizard"]},
  {name:"Telekinesis",school:"Transmutation",level:5,classes:["Sorcerer","Wizard"]},
  {name:"Teleport",school:"Conjuration",level:5,classes:["Sorcerer","Wizard"]},
  {name:"Transmute Rock to Mud",school:"Transmutation",level:5,classes:["Druid","Sorcerer","Wizard"]},
  {name:"Wall of Force",school:"Evocation",level:5,classes:["Sorcerer","Wizard"]},
  {name:"Wall of Stone",school:"Conjuration",level:5,classes:["Cleric","Druid","Sorcerer","Wizard"]},
  {name:"Waves of Fatigue",school:"Necromancy",level:5,classes:["Sorcerer","Wizard"]},
  // 6th level
  {name:"Acid Fog",school:"Conjuration",level:6,classes:["Sorcerer","Wizard"]},
  {name:"Analyze Dweomer",school:"Divination",level:6,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Antimagic Field",school:"Abjuration",level:6,classes:["Cleric","Sorcerer","Wizard"]},
  {name:"Chain Lightning",school:"Evocation",level:6,classes:["Sorcerer","Wizard"]},
  {name:"Circle of Death",school:"Necromancy",level:6,classes:["Sorcerer","Wizard"]},
  {name:"Contingency",school:"Evocation",level:6,classes:["Sorcerer","Wizard"]},
  {name:"Control Water",school:"Transmutation",level:6,classes:["Cleric","Druid","Sorcerer","Wizard"]},
  {name:"Create Undead",school:"Necromancy",level:6,classes:["Cleric","Sorcerer","Wizard"]},
  {name:"Disintegrate",school:"Transmutation",level:6,classes:["Sorcerer","Wizard"]},
  {name:"Eyebite",school:"Necromancy",level:6,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Find the Path",school:"Divination",level:6,classes:["Bard","Cleric","Druid"]},
  {name:"Flesh to Stone",school:"Transmutation",level:6,classes:["Sorcerer","Wizard"]},
  {name:"Forceful Hand",school:"Evocation",level:6,classes:["Sorcerer","Wizard"]},
  {name:"Freezing Sphere",school:"Evocation",level:6,classes:["Sorcerer","Wizard"]},
  {name:"Geas/Quest",school:"Enchantment",level:6,classes:["Bard","Cleric","Sorcerer","Wizard"]},
  {name:"Globe of Invulnerability",school:"Abjuration",level:6,classes:["Sorcerer","Wizard"]},
  {name:"Guards and Wards",school:"Abjuration",level:6,classes:["Sorcerer","Wizard"]},
  {name:"Heroes' Feast",school:"Conjuration",level:6,classes:["Cleric"]},
  {name:"Irresistible Dance",school:"Enchantment",level:6,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Legend Lore",school:"Divination",level:6,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Mass Suggestion",school:"Enchantment",level:6,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Mislead",school:"Illusion",level:6,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Move Earth",school:"Transmutation",level:6,classes:["Druid","Sorcerer","Wizard"]},
  {name:"Permanent Image",school:"Illusion",level:6,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Programmed Image",school:"Illusion",level:6,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Stone to Flesh",school:"Transmutation",level:6,classes:["Sorcerer","Wizard"]},
  {name:"Summon Monster VI",school:"Conjuration",level:6,classes:["Cleric","Sorcerer","Wizard"]},
  {name:"Symbol of Fear",school:"Necromancy",level:6,classes:["Cleric","Sorcerer","Wizard"]},
  {name:"Symbol of Persuasion",school:"Enchantment",level:6,classes:["Cleric","Sorcerer","Wizard"]},
  {name:"Transformation",school:"Transmutation",level:6,classes:["Sorcerer","Wizard"]},
  {name:"True Seeing",school:"Divination",level:6,classes:["Cleric","Druid","Sorcerer","Wizard"]},
  {name:"Undeath to Death",school:"Necromancy",level:6,classes:["Cleric","Sorcerer","Wizard"]},
  {name:"Veil",school:"Illusion",level:6,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Wall of Iron",school:"Conjuration",level:6,classes:["Sorcerer","Wizard"]},
  // 7th level
  {name:"Animate Plants",school:"Transmutation",level:7,classes:["Druid"]},
  {name:"Arcane Sight (Greater)",school:"Divination",level:7,classes:["Sorcerer","Wizard"]},
  {name:"Banishment",school:"Abjuration",level:7,classes:["Cleric","Sorcerer","Wizard"]},
  {name:"Control Undead",school:"Necromancy",level:7,classes:["Sorcerer","Wizard"]},
  {name:"Control Weather",school:"Transmutation",level:7,classes:["Cleric","Druid","Sorcerer","Wizard"]},
  {name:"Delayed Blast Fireball",school:"Evocation",level:7,classes:["Sorcerer","Wizard"]},
  {name:"Ethereal Jaunt",school:"Transmutation",level:7,classes:["Cleric","Sorcerer","Wizard"]},
  {name:"Finger of Death",school:"Necromancy",level:7,classes:["Druid","Sorcerer","Wizard"]},
  {name:"Forcecage",school:"Evocation",level:7,classes:["Sorcerer","Wizard"]},
  {name:"Grasping Hand",school:"Evocation",level:7,classes:["Sorcerer","Wizard"]},
  {name:"Hold Person (Mass)",school:"Enchantment",level:7,classes:["Sorcerer","Wizard"]},
  {name:"Insanity",school:"Enchantment",level:7,classes:["Sorcerer","Wizard"]},
  {name:"Invisibility (Mass)",school:"Illusion",level:7,classes:["Sorcerer","Wizard"]},
  {name:"Limited Wish",school:"Universal",level:7,classes:["Sorcerer","Wizard"]},
  {name:"Mage's Sword",school:"Evocation",level:7,classes:["Sorcerer","Wizard"]},
  {name:"Phase Door",school:"Conjuration",level:7,classes:["Sorcerer","Wizard"]},
  {name:"Plane Shift",school:"Conjuration",level:7,classes:["Cleric","Sorcerer","Wizard"]},
  {name:"Power Word Blind",school:"Enchantment",level:7,classes:["Sorcerer","Wizard"]},
  {name:"Prismatic Spray",school:"Evocation",level:7,classes:["Sorcerer","Wizard"]},
  {name:"Project Image",school:"Illusion",level:7,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Reverse Gravity",school:"Transmutation",level:7,classes:["Druid","Sorcerer","Wizard"]},
  {name:"Sequester",school:"Abjuration",level:7,classes:["Sorcerer","Wizard"]},
  {name:"Spell Turning",school:"Abjuration",level:7,classes:["Sorcerer","Wizard"]},
  {name:"Simulacrum",school:"Illusion",level:7,classes:["Sorcerer","Wizard"]},
  {name:"Statue",school:"Transmutation",level:7,classes:["Sorcerer","Wizard"]},
  {name:"Summon Monster VII",school:"Conjuration",level:7,classes:["Cleric","Sorcerer","Wizard"]},
  {name:"Symbol of Stunning",school:"Enchantment",level:7,classes:["Cleric","Sorcerer","Wizard"]},
  {name:"Symbol of Weakness",school:"Necromancy",level:7,classes:["Cleric","Sorcerer","Wizard"]},
  {name:"Teleport (Greater)",school:"Conjuration",level:7,classes:["Sorcerer","Wizard"]},
  {name:"Teleport Object",school:"Conjuration",level:7,classes:["Sorcerer","Wizard"]},
  {name:"Vision",school:"Divination",level:7,classes:["Sorcerer","Wizard"]},
  {name:"Waves of Exhaustion",school:"Necromancy",level:7,classes:["Sorcerer","Wizard"]},
  // 8th level
  {name:"Antipathy",school:"Enchantment",level:8,classes:["Druid","Sorcerer","Wizard"]},
  {name:"Binding",school:"Enchantment",level:8,classes:["Sorcerer","Wizard"]},
  {name:"Charm Monster (Mass)",school:"Enchantment",level:8,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Clenched Fist",school:"Evocation",level:8,classes:["Sorcerer","Wizard"]},
  {name:"Clone",school:"Necromancy",level:8,classes:["Sorcerer","Wizard"]},
  {name:"Create Greater Undead",school:"Necromancy",level:8,classes:["Cleric","Sorcerer","Wizard"]},
  {name:"Demand",school:"Enchantment",level:8,classes:["Sorcerer","Wizard"]},
  {name:"Dimensional Lock",school:"Abjuration",level:8,classes:["Cleric","Sorcerer","Wizard"]},
  {name:"Discern Location",school:"Divination",level:8,classes:["Cleric","Sorcerer","Wizard"]},
  {name:"Horrid Wilting",school:"Necromancy",level:8,classes:["Sorcerer","Wizard"]},
  {name:"Incendiary Cloud",school:"Conjuration",level:8,classes:["Sorcerer","Wizard"]},
  {name:"Iron Body",school:"Transmutation",level:8,classes:["Sorcerer","Wizard"]},
  {name:"Maze",school:"Conjuration",level:8,classes:["Sorcerer","Wizard"]},
  {name:"Mind Blank",school:"Abjuration",level:8,classes:["Sorcerer","Wizard"]},
  {name:"Moment of Prescience",school:"Divination",level:8,classes:["Sorcerer","Wizard"]},
  {name:"Polar Ray",school:"Evocation",level:8,classes:["Sorcerer","Wizard"]},
  {name:"Power Word Stun",school:"Enchantment",level:8,classes:["Sorcerer","Wizard"]},
  {name:"Prismatic Wall",school:"Abjuration",level:8,classes:["Sorcerer","Wizard"]},
  {name:"Protection from Spells",school:"Abjuration",level:8,classes:["Sorcerer","Wizard"]},
  {name:"Scintillating Pattern",school:"Illusion",level:8,classes:["Sorcerer","Wizard"]},
  {name:"Screen",school:"Illusion",level:8,classes:["Sorcerer","Wizard"]},
  {name:"Shadow Evocation (Greater)",school:"Illusion",level:8,classes:["Sorcerer","Wizard"]},
  {name:"Shout (Greater)",school:"Evocation",level:8,classes:["Bard","Sorcerer","Wizard"]},
  {name:"Stormrage",school:"Transmutation",level:8,classes:["Druid"]},
  {name:"Summon Monster VIII",school:"Conjuration",level:8,classes:["Cleric","Sorcerer","Wizard"]},
  {name:"Sunburst",school:"Evocation",level:8,classes:["Cleric","Druid","Sorcerer","Wizard"]},
  {name:"Symbol of Death",school:"Necromancy",level:8,classes:["Cleric","Sorcerer","Wizard"]},
  {name:"Symbol of Insanity",school:"Enchantment",level:8,classes:["Cleric","Sorcerer","Wizard"]},
  {name:"Sympathy",school:"Enchantment",level:8,classes:["Druid","Sorcerer","Wizard"]},
  {name:"Temporal Stasis",school:"Transmutation",level:8,classes:["Sorcerer","Wizard"]},
  {name:"Trap the Soul",school:"Conjuration",level:8,classes:["Sorcerer","Wizard"]},
  // 9th level
  {name:"Astral Projection",school:"Necromancy",level:9,classes:["Cleric","Sorcerer","Wizard"]},
  {name:"Crushing Hand",school:"Evocation",level:9,classes:["Sorcerer","Wizard"]},
  {name:"Dominate Monster",school:"Enchantment",level:9,classes:["Sorcerer","Wizard"]},
  {name:"Energy Drain",school:"Necromancy",level:9,classes:["Cleric","Sorcerer","Wizard"]},
  {name:"Etherealness",school:"Transmutation",level:9,classes:["Cleric","Sorcerer","Wizard"]},
  {name:"Foresight",school:"Divination",level:9,classes:["Druid","Sorcerer","Wizard"]},
  {name:"Gate",school:"Conjuration",level:9,classes:["Cleric","Sorcerer","Wizard"]},
  {name:"Hold Monster (Mass)",school:"Enchantment",level:9,classes:["Sorcerer","Wizard"]},
  {name:"Imprisonment",school:"Abjuration",level:9,classes:["Sorcerer","Wizard"]},
  {name:"Meteor Swarm",school:"Evocation",level:9,classes:["Sorcerer","Wizard"]},
  {name:"Mage's Disjunction",school:"Abjuration",level:9,classes:["Sorcerer","Wizard"]},
  {name:"Power Word Kill",school:"Enchantment",level:9,classes:["Sorcerer","Wizard"]},
  {name:"Prismatic Sphere",school:"Abjuration",level:9,classes:["Sorcerer","Wizard"]},
  {name:"Refuge",school:"Conjuration",level:9,classes:["Cleric","Sorcerer","Wizard"]},
  {name:"Shades",school:"Illusion",level:9,classes:["Sorcerer","Wizard"]},
  {name:"Shapechange",school:"Transmutation",level:9,classes:["Druid","Sorcerer","Wizard"]},
  {name:"Soul Bind",school:"Necromancy",level:9,classes:["Cleric","Sorcerer","Wizard"]},
  {name:"Storm of Vengeance",school:"Conjuration",level:9,classes:["Cleric","Druid"]},
  {name:"Summon Monster IX",school:"Conjuration",level:9,classes:["Cleric","Sorcerer","Wizard"]},
  {name:"Time Stop",school:"Transmutation",level:9,classes:["Sorcerer","Wizard"]},
  {name:"Teleportation Circle",school:"Conjuration",level:9,classes:["Sorcerer","Wizard"]},
  {name:"True Resurrection",school:"Conjuration",level:9,classes:["Cleric"]},
  {name:"Weird",school:"Illusion",level:9,classes:["Sorcerer","Wizard"]},
  {name:"Wish",school:"Universal",level:9,classes:["Sorcerer","Wizard"]},
  {name:"Wail of the Banshee",school:"Necromancy",level:9,classes:["Sorcerer","Wizard"]},
];

// Psionic power library for Browse & Restrict
const POWER_LIBRARY = [
  // Psion/Wilder 1st
  {name:"Astral Traveler",level:1,discipline:"Psychoportation",classes:["Psion","Wilder"]},
  {name:"Attraction",level:1,discipline:"Telepathy",classes:["Psion"]},
  {name:"Bolt",level:1,discipline:"Psychokinesis",classes:["Psion","Wilder"]},
  {name:"Call to Mind",level:1,discipline:"Clairsentience",classes:["Psion"]},
  {name:"Catfall",level:1,discipline:"Psychoportation",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Charm, Psionic",level:1,discipline:"Telepathy",classes:["Psion","Wilder"]},
  {name:"Conceal Thoughts",level:1,discipline:"Telepathy",classes:["Psion","Wilder"]},
  {name:"Control Flames",level:1,discipline:"Psychokinesis",classes:["Psion"]},
  {name:"Control Light",level:1,discipline:"Psychokinesis",classes:["Psion"]},
  {name:"Create Sound",level:1,discipline:"Metacreativity",classes:["Psion"]},
  {name:"Crystal Shard",level:1,discipline:"Metacreativity",classes:["Psion","Wilder"]},
  {name:"Daze, Psionic",level:1,discipline:"Telepathy",classes:["Psion","Wilder"]},
  {name:"Deceleration",level:1,discipline:"Psychoportation",classes:["Psion"]},
  {name:"Déjà Vu",level:1,discipline:"Telepathy",classes:["Psion","Wilder"]},
  {name:"Demoralize",level:1,discipline:"Telepathy",classes:["Psion","Wilder"]},
  {name:"Detect Psionics",level:1,discipline:"Clairsentience",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Disable",level:1,discipline:"Telepathy",classes:["Psion"]},
  {name:"Dissipating Touch",level:1,discipline:"Psychokinesis",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Distract",level:1,discipline:"Telepathy",classes:["Psion","Wilder"]},
  {name:"Ecto Protection",level:1,discipline:"Metacreativity",classes:["Psion"]},
  {name:"Empathy",level:1,discipline:"Telepathy",classes:["Psion","Wilder"]},
  {name:"Empty Mind",level:1,discipline:"Telepathy",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Energy Ray",level:1,discipline:"Psychokinesis",classes:["Psion","Wilder"]},
  {name:"Entangling Ectoplasm",level:1,discipline:"Metacreativity",classes:["Psion","Wilder"]},
  {name:"Far Hand",level:1,discipline:"Psychokinesis",classes:["Psion","Wilder"]},
  {name:"Float",level:1,discipline:"Psychoportation",classes:["Psion","Wilder"]},
  {name:"Force Screen",level:1,discipline:"Psychokinesis",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Grease, Psionic",level:1,discipline:"Metacreativity",classes:["Psion"]},
  {name:"Hammer",level:1,discipline:"Psychokinesis",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Inertial Armor",level:1,discipline:"Psychokinesis",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Know Direction and Location",level:1,discipline:"Clairsentience",classes:["Psion"]},
  {name:"Matter Agitation",level:1,discipline:"Psychokinesis",classes:["Psion","Wilder"]},
  {name:"Mind Thrust",level:1,discipline:"Telepathy",classes:["Psion","Wilder"]},
  {name:"Missive",level:1,discipline:"Telepathy",classes:["Psion","Wilder"]},
  {name:"My Light",level:1,discipline:"Psychokinesis",classes:["Psion","Wilder"]},
  {name:"Precognition (Defensive)",level:1,discipline:"Clairsentience",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Prescience (Offensive)",level:1,discipline:"Clairsentience",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Sense Link",level:1,discipline:"Telepathy",classes:["Psion"]},
  {name:"Skate",level:1,discipline:"Psychoportation",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Stomp",level:1,discipline:"Psychokinesis",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Synesthete",level:1,discipline:"Telepathy",classes:["Psion","Wilder"]},
  {name:"Telempathic Projection",level:1,discipline:"Telepathy",classes:["Psion","Wilder"]},
  {name:"Vigor",level:1,discipline:"Psychometabolism",classes:["Psion","Wilder","Psychic Warrior"]},
  // 2nd level
  {name:"Biofeedback",level:2,discipline:"Psychometabolism",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Body Equilibrium",level:2,discipline:"Psychometabolism",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Clairvoyant Sense",level:2,discipline:"Clairsentience",classes:["Psion","Wilder"]},
  {name:"Cloud Mind",level:2,discipline:"Telepathy",classes:["Psion","Wilder"]},
  {name:"Concussion Blast",level:2,discipline:"Psychokinesis",classes:["Psion","Wilder"]},
  {name:"Control Sound",level:2,discipline:"Psychokinesis",classes:["Psion"]},
  {name:"Detect Hostile Intent",level:2,discipline:"Telepathy",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Ego Whip",level:2,discipline:"Telepathy",classes:["Psion","Wilder"]},
  {name:"Elfsight",level:2,discipline:"Psychometabolism",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Energy Adaptation (Specified)",level:2,discipline:"Psychometabolism",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Energy Push",level:2,discipline:"Psychokinesis",classes:["Psion","Wilder"]},
  {name:"Energy Stun",level:2,discipline:"Psychokinesis",classes:["Psion","Wilder"]},
  {name:"Feat Leech",level:2,discipline:"Clairsentience",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Id Insinuation",level:2,discipline:"Telepathy",classes:["Psion","Wilder"]},
  {name:"Inflict Pain",level:2,discipline:"Telepathy",classes:["Psion","Wilder"]},
  {name:"Knock, Psionic",level:2,discipline:"Psychoportation",classes:["Psion"]},
  {name:"Levitate, Psionic",level:2,discipline:"Psychoportation",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Mental Disruption",level:2,discipline:"Telepathy",classes:["Psion","Wilder"]},
  {name:"Missive (Mass)",level:2,discipline:"Telepathy",classes:["Psion"]},
  {name:"Psionic Lock",level:2,discipline:"Psychoportation",classes:["Psion"]},
  {name:"Read Thoughts",level:2,discipline:"Telepathy",classes:["Psion","Wilder"]},
  {name:"Share Pain",level:2,discipline:"Telepathy",classes:["Psion","Wilder"]},
  {name:"Specified Energy Adaptation",level:2,discipline:"Psychometabolism",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Swarm of Crystals",level:2,discipline:"Metacreativity",classes:["Psion","Wilder"]},
  {name:"Thought Shield",level:2,discipline:"Telepathy",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Wall Walker",level:2,discipline:"Psychoportation",classes:["Psion","Wilder","Psychic Warrior"]},
  // 3rd level
  {name:"Body Purification",level:3,discipline:"Psychometabolism",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Danger Sense",level:3,discipline:"Clairsentience",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Darkvision, Psionic",level:3,discipline:"Psychometabolism",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Dismiss Ectoplasm",level:3,discipline:"Metacreativity",classes:["Psion","Wilder"]},
  {name:"Dispel Psionics",level:3,discipline:"Psychokinesis",classes:["Psion","Wilder"]},
  {name:"Energy Bolt",level:3,discipline:"Psychokinesis",classes:["Psion","Wilder"]},
  {name:"Energy Burst",level:3,discipline:"Psychokinesis",classes:["Psion","Wilder"]},
  {name:"Energy Retort",level:3,discipline:"Psychokinesis",classes:["Psion","Wilder"]},
  {name:"Energy Wall",level:3,discipline:"Psychokinesis",classes:["Psion","Wilder"]},
  {name:"Ectoplasmic Form",level:3,discipline:"Psychometabolism",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"False Sensory Input",level:3,discipline:"Telepathy",classes:["Psion","Wilder"]},
  {name:"Fate Link",level:3,discipline:"Clairsentience",classes:["Psion","Wilder"]},
  {name:"Graft Weapon",level:3,discipline:"Psychometabolism",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Keen Edge, Psionic",level:3,discipline:"Metacreativity",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Mental Barrier",level:3,discipline:"Clairsentience",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Mind Trap",level:3,discipline:"Telepathy",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Psionic Blast",level:3,discipline:"Telepathy",classes:["Psion","Wilder"]},
  {name:"Telekinetic Force",level:3,discipline:"Psychokinesis",classes:["Psion","Wilder"]},
  {name:"Telekinetic Thrust",level:3,discipline:"Psychokinesis",classes:["Psion","Wilder"]},
  {name:"Time Hop",level:3,discipline:"Psychoportation",classes:["Psion","Wilder"]},
  {name:"Touchsight",level:3,discipline:"Clairsentience",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Ubiquitous Vision",level:3,discipline:"Clairsentience",classes:["Psion","Wilder","Psychic Warrior"]},
  // 4th level
  {name:"Aura Sight",level:4,discipline:"Clairsentience",classes:["Psion","Wilder"]},
  {name:"Correspond",level:4,discipline:"Telepathy",classes:["Psion"]},
  {name:"Death Urge",level:4,discipline:"Telepathy",classes:["Psion","Wilder"]},
  {name:"Detect Remote Viewing",level:4,discipline:"Clairsentience",classes:["Psion","Wilder"]},
  {name:"Dimension Door, Psionic",level:4,discipline:"Psychoportation",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Divination, Psionic",level:4,discipline:"Clairsentience",classes:["Psion"]},
  {name:"Dominate, Psionic",level:4,discipline:"Telepathy",classes:["Psion","Wilder"]},
  {name:"Energy Adaptation",level:4,discipline:"Psychometabolism",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Freedom of Movement, Psionic",level:4,discipline:"Psychoportation",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Intellect Fortress",level:4,discipline:"Telepathy",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Matter Manipulation",level:4,discipline:"Metacreativity",classes:["Psion"]},
  {name:"Mindwipe",level:4,discipline:"Telepathy",classes:["Psion","Wilder"]},
  {name:"Personality Parasite",level:4,discipline:"Telepathy",classes:["Psion","Wilder"]},
  {name:"Power Leech",level:4,discipline:"Telepathy",classes:["Psion","Wilder"]},
  {name:"Psychic Reformation",level:4,discipline:"Telepathy",classes:["Psion"]},
  {name:"Telekinetic Maneuver",level:4,discipline:"Psychokinesis",classes:["Psion","Wilder"]},
  {name:"Trace Teleport",level:4,discipline:"Clairsentience",classes:["Psion"]},
  {name:"Wall of Ectoplasm",level:4,discipline:"Metacreativity",classes:["Psion","Wilder"]},
  // 5th level
  {name:"Adapt Body",level:5,discipline:"Psychometabolism",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Catapsi",level:5,discipline:"Telepathy",classes:["Psion","Wilder"]},
  {name:"Ectoplasmic Shambler",level:5,discipline:"Metacreativity",classes:["Psion","Wilder"]},
  {name:"Incarnate",level:5,discipline:"Metacreativity",classes:["Psion"]},
  {name:"Leech Field",level:5,discipline:"Psychometabolism",classes:["Psion","Wilder"]},
  {name:"Major Creation, Psionic",level:5,discipline:"Metacreativity",classes:["Psion"]},
  {name:"Plane Shift, Psionic",level:5,discipline:"Psychoportation",classes:["Psion","Wilder"]},
  {name:"Power Resistance",level:5,discipline:"Clairsentience",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Psychic Crush",level:5,discipline:"Telepathy",classes:["Psion","Wilder"]},
  {name:"Shatter Mind Blank",level:5,discipline:"Telepathy",classes:["Psion","Wilder"]},
  {name:"Teleport, Psionic",level:5,discipline:"Psychoportation",classes:["Psion","Wilder"]},
  {name:"True Seeing, Psionic",level:5,discipline:"Clairsentience",classes:["Psion","Wilder","Psychic Warrior"]},
  // 6th-9th (key powers)
  {name:"Aura Alteration",level:6,discipline:"Telepathy",classes:["Psion","Wilder"]},
  {name:"Brutalize Wounds",level:6,discipline:"Psychometabolism",classes:["Psion","Wilder"]},
  {name:"Cloud Mind (Mass)",level:6,discipline:"Telepathy",classes:["Psion","Wilder"]},
  {name:"Co-opt Concentration",level:6,discipline:"Telepathy",classes:["Psion"]},
  {name:"Disintegrate, Psionic",level:6,discipline:"Psychokinesis",classes:["Psion","Wilder"]},
  {name:"Mind Switch",level:6,discipline:"Telepathy",classes:["Psion"]},
  {name:"Null Psionics Field",level:6,discipline:"Psychokinesis",classes:["Psion","Wilder"]},
  {name:"Temporal Acceleration",level:6,discipline:"Psychoportation",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Retrieve",level:6,discipline:"Psychoportation",classes:["Psion","Wilder"]},
  {name:"Decerebrate",level:7,discipline:"Telepathy",classes:["Psion","Wilder"]},
  {name:"Divert Teleport",level:7,discipline:"Psychoportation",classes:["Psion"]},
  {name:"Energy Conversion",level:7,discipline:"Psychokinesis",classes:["Psion","Wilder"]},
  {name:"Energy Wave",level:7,discipline:"Psychokinesis",classes:["Psion","Wilder"]},
  {name:"Ethereal Jaunt, Psionic",level:7,discipline:"Psychoportation",classes:["Psion","Wilder"]},
  {name:"Moment of Prescience, Psionic",level:7,discipline:"Clairsentience",classes:["Psion","Wilder"]},
  {name:"Oak Body",level:7,discipline:"Psychometabolism",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Ultrablast",level:7,discipline:"Telepathy",classes:["Psion","Wilder"]},
  {name:"Bend Reality",level:8,discipline:"Clairsentience",classes:["Psion","Wilder"]},
  {name:"Iron Body, Psionic",level:8,discipline:"Psychometabolism",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Matter Manipulation",level:8,discipline:"Metacreativity",classes:["Psion"]},
  {name:"Mind Blank, Personal",level:8,discipline:"Telepathy",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Recall Death",level:8,discipline:"Telepathy",classes:["Psion","Wilder"]},
  {name:"Shadow Body",level:8,discipline:"Psychometabolism",classes:["Psion","Wilder"]},
  {name:"Teleport (Greater), Psionic",level:8,discipline:"Psychoportation",classes:["Psion","Wilder"]},
  {name:"True Metabolism",level:8,discipline:"Psychometabolism",classes:["Psion","Wilder","Psychic Warrior"]},
  {name:"Affinity Field",level:9,discipline:"Psychometabolism",classes:["Psion","Wilder"]},
  {name:"Apopsi",level:9,discipline:"Telepathy",classes:["Psion"]},
  {name:"Assimilate",level:9,discipline:"Psychometabolism",classes:["Psion","Wilder"]},
  {name:"Etherealness, Psionic",level:9,discipline:"Psychoportation",classes:["Psion","Wilder"]},
  {name:"Microcosm",level:9,discipline:"Telepathy",classes:["Psion","Wilder"]},
  {name:"Psychic Chirurgery",level:9,discipline:"Telepathy",classes:["Psion"]},
  {name:"Reality Revision",level:9,discipline:"Clairsentience",classes:["Psion","Wilder"]},
  {name:"Timeless Body",level:9,discipline:"Psychoportation",classes:["Psion","Wilder","Psychic Warrior"]},
];
