import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { DmProvider } from "@/context/DmContext";
import { ContentPackProvider } from "@/context/ContentPackContext";
import { CharacterProvider } from "@/context/CharacterContext";

const EMPTY_PACK = { races: [], classes: [], feats: [], spells: [], powers: [], invocations: [], campaigns: [] };

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
          <DmProvider>
            <ContentPackProvider pack={EMPTY_PACK}>
              <CharacterProvider>
                {children}
              </CharacterProvider>
            </ContentPackProvider>
          </DmProvider>
        </body>
    </html>
  );
}
